{{
    config(

        materialized='table',  
        dist='account_id', 
        sort='account_id'       
        )
}}


with sch as (
select
    parent_id,
    BOOL_OR(state_initiative_c) as school_state_initiative_c,
    BOOL_OR(district_state_initiative_c) as school_district_state_initiative_c,
    BOOL_OR(state_eligible_or_initiative_c) as school_state_eligible_or_initiative_c
FROM {{ source('fivetran_salesforce_quickstart', 'account') }}
where org_type_c='School'
group by parent_id
)
, sfdc_data as (
  select
    --SFDC columns
sfdc_account.Id,
    sfdc_account.name,
    --
sfdc_account.account_last_activity_date_c,
    sfdc_account.account_lifecycle_stage_c,
    sfdc_account.account_management_type_c,
    sfdc_account.act_id_c,
    sfdc_account.actively_prospecting_c,
    sfdc_account.activity_metric_id,
    sfdc_account.activity_metric_rollup_id,
    sfdc_account.ae_or_isr_c,
    sfdc_account.agile_id_c,
    sfdc_account.agile_lms_c,
    sfdc_account.agileed_agile_ed_insert_c,
    sfdc_account.agileed_agile_ed_key_c,
    sfdc_account.agileed_agile_ed_latest_update_date_c,
    sfdc_account.agileed_agile_ed_parent_key_c,
    sfdc_account.agileed_agile_ed_status_c,
    sfdc_account.agileed_agile_ed_up_to_date_c,
    sfdc_account.agileed_agileed_do_not_update_c,
    sfdc_account.agileed_connect_link_changed_personnel_titles_c,
    sfdc_account.agileed_connect_link_district_key_c,
    sfdc_account.agileed_connect_link_file_type_c,
    sfdc_account.agileed_connect_link_hierarchized_personnel_c,
    sfdc_account.agileed_connect_link_licensed_status_c,
    sfdc_account.agileed_connect_link_personnel_roles_c,
    sfdc_account.agileed_connect_link_personnel_titles_c,
    sfdc_account.agileed_last_sync_c,
    sfdc_account.agileed_parent_pending_c,
    sfdc_account.agileed_personnel_last_sync_c,
    sfdc_account.alt_phone_c,
    sfdc_account.cares_act_allocation_c,
    sfdc_account.category_c,
    sfdc_account.check_national_id_c,
    sfdc_account.closed_district_tx_adoption_c,
    sfdc_account.code_monkey_customer_c,
    sfdc_account.codester_id_c,
    sfdc_account.codesters_account_to_be_migrated_to_prod_c,
    sfdc_account.codesters_customer_2_c,
    sfdc_account.codesters_customer_dedupe_flag_c,
    sfdc_account.company_domain_name_c,
    sfdc_account.completed_onboarding_c,
    sfdc_account.computer_os_c,
    sfdc_account.contracted_roll_up_c,
    sfdc_account.county_name_c,
    sfdc_account.created_by_id,
    sfdc_account.created_date,
    sfdc_account.csm_email_c,
    sfdc_account.csm_name_c,
    sfdc_account.current_renewal_arr_c,
    sfdc_account.current_total_ultimate_parent_c,
    sfdc_account.customer_type_c,
    sfdc_account.data_quality_description_c,
    sfdc_account.data_quality_score_c,
    sfdc_account.de_identified_district_c,
    sfdc_account.description,
    sfdc_account.detailed_grade_c,
    sfdc_account.district_c,
    sfdc_account.district_easy_code_tam_c,
    sfdc_account.district_easy_tech_tam_c,
    sfdc_account.district_elementary_teachers_c,
    sfdc_account.district_enrollment_c,
    sfdc_account.district_expansion_potential_c,
    sfdc_account.district_faculty_library_media_fte_c,
    sfdc_account.district_instructional_expenditures_c,
    sfdc_account.district_k_8_enrollment_c,
    sfdc_account.district_kindergarten_teachers_c,
    sfdc_account.district_local_revenue_cities_c,
    sfdc_account.district_local_revenue_other_leas_c,
    sfdc_account.district_local_revenue_other_taxes_c,
    sfdc_account.district_local_revenue_property_taxes_c,
    sfdc_account.district_nces_c,
    sfdc_account.district_presence_c,
    sfdc_account.district_state_initiative_c,
    sfdc_account.district_total_capital_outlay_c,
    sfdc_account.district_total_expenditures_c,
    sfdc_account.district_total_expense_per_student_c,
    sfdc_account.district_total_fed_revenue_c,
    sfdc_account.district_total_local_revenue_c,
    sfdc_account.district_total_revenue_c,
    sfdc_account.district_total_state_revenue_c,
    sfdc_account.district_total_tam_c,
    sfdc_account.district_type_c,
    sfdc_account.dq_opportunities_c,
    sfdc_account.easy_tech_customer_c,
    sfdc_account.easy_tech_tam_c,
    sfdc_account.easy_tech_tam_captured_c,
    sfdc_account.ec_tam_c,
    sfdc_account.education_climate_index_c,
    sfdc_account.education_type_c,
    sfdc_account.eighth_grade_enrollment_c,
    sfdc_account.email_domain_c,
    sfdc_account.enrollment_advanced_placement_c,
    sfdc_account.enrollment_band_c,
    sfdc_account.enrollment_tier_c,
    sfdc_account.esser_funding_c,
    sfdc_account.et_tam_c,
    sfdc_account.exes_campaign_c,
    sfdc_account.fifth_grade_enrollment_c,
    sfdc_account.first_grade_enrollment_c,
    sfdc_account.first_name_c,
    sfdc_account.fiscal_career_and_tech_federal_c,
    sfdc_account.fiscal_career_and_tech_state_c,
    sfdc_account.fiscal_career_and_tech_teacher_salar_c,
    sfdc_account.fiscal_title_i_eligible_school_c,
    sfdc_account.fiscal_title_i_funding_c,
    sfdc_account.fiscal_title_i_percentage_c,
    sfdc_account.fiscal_title_i_school_c,
    sfdc_account.fiscal_title_i_school_yes_no_c,
    sfdc_account.fiscal_title_i_schoolwide_c,
    sfdc_account.fiscal_title_i_schoolwide_yes_no_c,
    sfdc_account.free_lunch_students_c,
    sfdc_account.free_reduced_lunch_c,
    sfdc_account.gainsight_customer_c,
    sfdc_account.gainsight_house_c,
    sfdc_account.google_integration_c,
    sfdc_account.governor_c,
    sfdc_account.governor_s_party_affiliation_c,
    sfdc_account.grade_level_detail_c,
    sfdc_account.grade_levels_c,
    sfdc_account.has_codesters_child_accounts_c,
    sfdc_account.hi_speed_classroom_internet_c,
    sfdc_account.hi_speed_internet_c,
    sfdc_account.hml_title_i_funding_c,
    sfdc_account.hml_title_i_per_student_c,
    sfdc_account.house_account_c,
    sfdc_account.i_pad_schools_percent_c,
    sfdc_account.i_pads_for_instruction_c,
    sfdc_account.ima_coordinator_identified_c,
    sfdc_account.inst_uid_c,
    sfdc_account.k_12_enrollment_c,
    sfdc_account.k_5_enrollment_c,
    sfdc_account.k_8_district_presence_c,
    sfdc_account.k_8_enrollment_c,
    sfdc_account.key_account_c,
    sfdc_account.kindergarten_enrollment_c,
    sfdc_account.known_duplicate_c,
    sfdc_account.last_activity_date,
    sfdc_account.last_activity_logged_on_c,
    sfdc_account.last_modified_by_id,
    sfdc_account.last_modified_date,
    sfdc_account.last_name_c,
    sfdc_account.lcom_account_c,
    sfdc_account.lcom_account_class_c,
    sfdc_account.lcom_account_count_c,
    sfdc_account.lcom_organization_c,
    sfdc_account.lcom_organization_count_c,
    sfdc_account.lcom_organization_has_parent_c,
    sfdc_account.learn_dash_code_sent_c,
    sfdc_account.les_opp_c,
    sfdc_account.license_consumption_c,
    sfdc_account.map_tracker_c,
    sfdc_account.mdr_number_c,
    sfdc_account.mi_pilot_c,
    sfdc_account.multi_tiered_account_c,
    sfdc_account.name_with_lcom_organization_info_c,
    sfdc_account.national_district_id_c,
    sfdc_account.national_school_id_c,
    sfdc_account.nc_tier_1_c,
    sfdc_account.nces_lea_id_c,
    sfdc_account.nces_unique_id_c,
    sfdc_account.net_suite_id_c,
    sfdc_account.net_suite_link_c,
    sfdc_account.netsuite_account_number_c,
    sfdc_account.no_of_child_account_c,
    sfdc_account.nps_count_c,
    sfdc_account.nps_score_c,
    sfdc_account.nps_sum_c,
    sfdc_account.num_opps_c,
    sfdc_account.number_of_2020_opps_c,
    sfdc_account.number_of_active_easy_tech_subscriptions_c,
    sfdc_account.number_of_active_vidcode_subscriptions_c,
    sfdc_account.number_of_elementary_schools_c,
    sfdc_account.number_of_high_schools_c,
    sfdc_account.number_of_k_8_buildings_c,
    sfdc_account.number_of_middle_schools_c,
    sfdc_account.number_of_open_opportunities_c,
    sfdc_account.number_of_open_opps_c,
    sfdc_account.number_of_page_views_c,
    sfdc_account.number_of_renewal_opps_c,
    sfdc_account.number_of_schools_c,
    sfdc_account.number_of_sessions_c,
    sfdc_account.number_of_title_i_schools_c,
    sfdc_account.number_of_won_renewal_opportunities_c,
    sfdc_account.open_opportunity_amount_c,
    sfdc_account.open_renewal_opportunities_c,
    sfdc_account.org_type_c,
    sfdc_account.otc_provisioned_c,
    sfdc_account.owner_c,
    sfdc_account.owner_id,
    sfdc_account.owner_id_c,
    sfdc_account.owner_name_text_c,
    sfdc_account.parent_account_owner_c,
    sfdc_account.parent_and_child_match_c,
    sfdc_account.parent_churned_c,
    sfdc_account.parent_et_tam_c,
    sfdc_account.parent_gsid_c,
    sfdc_account.parent_id,
    sfdc_account.parent_long_name_c,
    sfdc_account.parent_mdr_c,
    sfdc_account.parent_name_c,
    sfdc_account.parent_name_proper_case_c,
    sfdc_account.parent_owner_id_c,
    sfdc_account.parent_uid_c,
    sfdc_account.pct_afro_amer_c,
    sfdc_account.pct_asian_c,
    sfdc_account.pct_hisp_c,
    sfdc_account.pct_multi_racial_c,
    sfdc_account.pct_native_c,
    sfdc_account.pct_white_c,
    sfdc_account.per_student_expenditures_c,
    sfdc_account.percent_students_ell_c,
    sfdc_account.phone,
    sfdc_account.photo_url,
    sfdc_account.platform_sync_c,
    sfdc_account.poverty_percent_under_age_18_c,
    sfdc_account.pre_k_enrollment_c,
    sfdc_account.priority_account_c,
    sfdc_account.record_type_c,
    sfdc_account.reduced_lunch_student_c,
    sfdc_account.reference_customer_c,
    sfdc_account.related_activity_c,
    sfdc_account.related_c,
    sfdc_account.renewal_forecast_segment_c,
    sfdc_account.resa_name_proper_c,
    sfdc_account.resa_uid_c,
    sfdc_account.sales_owner_field_c,
    sfdc_account.sales_support_rep_c,
    sfdc_account.sbqq_co_termed_contracts_combined_c,
    sfdc_account.sbqq_contract_co_termination_c,
    sfdc_account.sbqq_preserve_bundle_c,
    sfdc_account.school_enrollment_c,
    sfdc_account.school_id_c,
    sfdc_account.school_type_c,
    sfdc_account.school_year_end_c,
    sfdc_account.school_year_start_c,
    sfdc_account.schools_in_district_c,
    sfdc_account.state_eligible_or_initiative_c,
    sfdc_account.state_initiative_c,
    sfdc_account.state_profile_c,
    sfdc_account.state_program_eligible_c,
    sfdc_account.student_tam_c,
    sfdc_account.sync_district_c,
    sfdc_account.syncing_district_c,
    sfdc_account.system_modstamp,
    sfdc_account.target_account_c,
    sfdc_account.teachers_in_building_c,
    sfdc_account.technology_equipment_c,
    sfdc_account.technology_index_c,
    sfdc_account.technology_measure_c,
    sfdc_account.technology_supplies_and_purchases_c,
    sfdc_account.territory_c,
    sfdc_account.territory_list_c,
    sfdc_account.test_account_c,
    sfdc_account.tiered_service_level_c,
    sfdc_account.time_zone_c,
    sfdc_account.time_zone_raw_c,
    sfdc_account.time_zone_transformed_c,
    sfdc_account.title_iv_funding_21_st_century_grants_c,
    sfdc_account.title_iv_funding_student_support_c,
    sfdc_account.top_75_account_c,
    sfdc_account.total_credits_purchased_c,
    sfdc_account.total_number_of_schools_c,
    sfdc_account.total_renewal_arr_c,
    sfdc_account.trend_district_revenue_c,
    sfdc_account.trend_enrollment_c,
    sfdc_account.trend_federal_revenue_c,
    sfdc_account.trend_instructional_expenditures_c,
    sfdc_account.trend_local_revenue_c,
    sfdc_account.trend_state_revenue_c,
    sfdc_account.trend_title_i_revenue_c,
    sfdc_account.type,
    sfdc_account.ultimate_account_lifecycle_stage_c,
    sfdc_account.ultimate_account_owner_c,
    sfdc_account.ultimate_parent_account_c,
    sfdc_account.ultimate_parent_billing_state_c,
    sfdc_account.ultimate_parent_id_c,
    sfdc_account.ultimate_parent_total_renewal_arr_2_c,
    sfdc_account.urban_rural_c,
    sfdc_account.vidcode_customer_2_c,
    sfdc_account.virtual_school_c,
    sfdc_account.virtual_status_text_c,
    sfdc_account.website,
    sfdc_account.x_1_1_computing_c,
    sfdc_account.x_10_th_grade_enrollment_c,
    sfdc_account.x_11_th_grade_enrollment_c,
    sfdc_account.x_12_th_grade_enrollment_c,
    sfdc_account.x_2_nd_grade_enrollment_c,
    sfdc_account.x_2020_service_purchased_c,
    sfdc_account.x_21_csa_eol_c,
    sfdc_account.x_3_plms_c,
    sfdc_account.x_3_rd_grade_enrollment_c,
    sfdc_account.x_4_th_grade_enrollment_c,
    sfdc_account.x_6_th_grade_enrollment_c,
    sfdc_account.x_7_th_grade_enrollment_c,
    sfdc_account.x_9_th_grade_enrollment_c,
    sfdc_account.zendesk_domain_c,
    --School (some child accounts info)
sch.school_state_initiative_c as state_initiative_school,
    sch.school_district_state_initiative_c as district_state_initiative_school,
    sch.school_state_eligible_or_initiative_c as state_eligible_or_initiative_school,
    --District (some parent account info)
dist.state_initiative_c as state_initiative_district,
    dist.district_state_initiative_c as district_state_initiative_district,
    dist.state_eligible_or_initiative_c as state_eligible_or_initiative_district,
    --
lower(loc.lcom_platform_organization_id_c) lcom_organization_id
--
FROM {{ source('fivetran_salesforce_quickstart', 'account') }} sfdc_account
left outer join {{ source('fivetran_salesforce_quickstart', 'lcom_organization_c') }} loc
on sfdc_account.lcom_organization_c = loc.id
left outer join sch 
on sfdc_account.id=sch.parent_id
left outer join {{ source('fivetran_salesforce_quickstart', 'account') }} dist
on sfdc_account.parent_id=dist.id

)
, LCOM_data as (
  select
    --LCOM columns
o.organization_id,
    o.organization_name,
    o.organization_type,
    o.parent_organization_id,
    p.organization_name  as parent_organization_name,
    o.is_trial,
    o.is_demo,
    o.postal_code,
    o.state_province_key,
    sp.state_province_code,
    sp.state_province_name,
    o.country_code,
    c.country_name,
    c.alpha3_code,
    c.numeric_code,
    o.external_sis_id,
    o.nces_id,
    o.created_datetime,
    o.modified_datetime,
    o.deleted_datetime,
    m.salesforce_id,
    m.SFDC_Account_Id
FROM {{ source("dbo","organization") }}  o
left outer join {{ source("dbo","organization") }}  p
on o.parent_organization_id = p.organization_id
--
left outer join {{ source("dbo","state_province") }}  sp
on sp.state_province_key=o.state_province_key
--
left outer join {{ source("dbo","country") }}  c
on c.country_code=o.country_code
-- mapping to Salesforce Accounts
left outer join {{ ref("lcom_sfdc_acccount_mapping") }} m
on o.organization_id=m.organization_id

)

, data as (
select
    coalesce(LCOM_data.organization_id,
    SFDC_data.Id) as account_id,
    --LCOM columns
isnull(LCOM_data.organization_id,
    '{{ var("default_varchar") }}') as  lcom_organization_id,
    isnull(LCOM_data.organization_name,
    '{{ var("default_varchar") }}') as  lcom_organization_name,
    isnull(LCOM_data.organization_type,
    '{{ var("default_varchar") }}') as  lcom_organization_type,
    isnull(LCOM_data.parent_organization_id,
    '{{ var("default_ID") }}') as  lcom_parent_organization_id,
    isnull(LCOM_data.organization_name,
    '{{ var("default_varchar") }}') as  lcom_parent_organization_name,
    isnull(LCOM_data.is_trial,
    {{ var("default_boolean") }}) as  lcom_trial,
    isnull(LCOM_data.is_demo,
    {{ var("default_boolean") }}) as  lcom_demo,
    isnull(LCOM_data.postal_code,
    '{{ var("default_varchar") }}') as  lcom_postal_code,
    isnull(LCOM_data.state_province_key,
    '{{ var("default_varchar") }}') as  lcom_state_province_key,
    isnull(LCOM_data.state_province_code,
    '{{ var("default_varchar") }}') as  lcom_state_province_code,
    isnull(LCOM_data.state_province_name,
    '{{ var("default_varchar") }}') as  lcom_state_province_name,
    isnull(LCOM_data.country_code,
    '{{ var("default_varchar") }}')  as lcom_country_code,
    isnull(LCOM_data.country_name,
    '{{ var("default_varchar") }}') as  lcom_country_name,
    isnull(LCOM_data.alpha3_code,
    '{{ var("default_varchar") }}') as  lcom_alpha3_code,
    isnull(LCOM_data.numeric_code,
    '{{ var("default_varchar") }}') as  lcom_numeric_code,
    isnull(LCOM_data.external_sis_id,
    '{{ var("default_varchar") }}') as  lcom_external_sis_id,
    isnull(LCOM_data.nces_id,
    '{{ var("default_varchar") }}')  as lcom_nces_id,
    isnull(LCOM_data.created_datetime,
    '{{ var("default_date") }}') as  lcom_created_datetime,
    isnull(LCOM_data.modified_datetime,
    '{{ var("default_date") }}')  as lcom_modified_datetime,
    isnull(LCOM_data.deleted_datetime,
    '{{ var("default_date") }}')  as lcom_deleted_datetime,
    --SFDC columns
coalesce(LCOM_data.SFDC_account_id,
    SFDC_data.Id,
    '{{ var("default_varchar") }}') as SFDC_account_id,
    isnull(SFDC_data.name,
    '{{ var("default_varchar") }}') as SFDC_name,
    isnull(SFDC_data.account_last_activity_date_c,
    '{{ var("default_date") }}') as SFDC_account_last_activity_date,
    isnull(SFDC_data.account_lifecycle_stage_c,
    '{{ var("default_varchar") }}') as SFDC_account_lifecycle_stage,
    isnull(SFDC_data.account_management_type_c,
    '{{ var("default_varchar") }}') as SFDC_account_management_type,
    isnull(SFDC_data.act_id_c,
    '{{ var("default_varchar") }}') as SFDC_act_id,
    isnull(SFDC_data.actively_prospecting_c,
    {{ var("default_boolean") }}) as SFDC_actively_prospecting,
    isnull(SFDC_data.activity_metric_id,
    '{{ var("default_varchar") }}') as SFDC_activity_metric_id,
    isnull(SFDC_data.activity_metric_rollup_id,
    '{{ var("default_varchar") }}') as SFDC_activity_metric_rollup_id,
    isnull(SFDC_data.ae_or_isr_c,
    '{{ var("default_varchar") }}') as SFDC_ae_or_isr,
    isnull(SFDC_data.agile_id_c,
    '{{ var("default_varchar") }}') as SFDC_agile_id,
    isnull(SFDC_data.agile_lms_c,
    '{{ var("default_varchar") }}') as SFDC_agile_lms,
    isnull(SFDC_data.agileed_agile_ed_insert_c,
    {{ var("default_boolean") }}) as SFDC_agileed_agile_ed_insert,
    isnull(SFDC_data.agileed_agile_ed_key_c,
    '{{ var("default_varchar") }}') as SFDC_agileed_agile_ed_key,
    isnull(SFDC_data.agileed_agile_ed_latest_update_date_c,
    '{{ var("default_date") }}') as SFDC_agileed_agile_ed_latest_update_date,
    isnull(SFDC_data.agileed_agile_ed_parent_key_c,
    '{{ var("default_varchar") }}') as SFDC_agileed_agile_ed_parent_key,
    isnull(SFDC_data.agileed_agile_ed_status_c,
    '{{ var("default_varchar") }}') as SFDC_agileed_agile_ed_status,
    isnull(SFDC_data.agileed_agile_ed_up_to_date_c,
    {{ var("default_boolean") }}) as SFDC_agileed_agile_ed_up_to_date,
    isnull(SFDC_data.agileed_agileed_do_not_update_c,
    {{ var("default_boolean") }}) as SFDC_agileed_agileed_do_not_update,
    isnull(SFDC_data.agileed_connect_link_changed_personnel_titles_c,
    {{ var("default_numeric") }}) as SFDC_agileed_connect_link_changed_personnel_titles,
    isnull(SFDC_data.agileed_connect_link_district_key_c,
    '{{ var("default_varchar") }}') as SFDC_agileed_connect_link_district_key,
    isnull(SFDC_data.agileed_connect_link_file_type_c,
    '{{ var("default_varchar") }}') as SFDC_agileed_connect_link_file_type,
    isnull(SFDC_data.agileed_connect_link_hierarchized_personnel_c,
    {{ var("default_numeric") }}) as SFDC_agileed_connect_link_hierarchized_personnel,
    isnull(SFDC_data.agileed_connect_link_licensed_status_c,
    '{{ var("default_varchar") }}') as SFDC_agileed_connect_link_licensed_status,
    isnull(SFDC_data.agileed_connect_link_personnel_roles_c,
    {{ var("default_numeric") }}) as SFDC_agileed_connect_link_personnel_roles,
    isnull(SFDC_data.agileed_connect_link_personnel_titles_c,
    {{ var("default_numeric") }}) as SFDC_agileed_connect_link_personnel_titles,
    isnull(SFDC_data.agileed_last_sync_c,
    '{{ var("default_date") }}') as SFDC_agileed_last_sync,
    isnull(SFDC_data.agileed_parent_pending_c,
    {{ var("default_boolean") }}) as SFDC_agileed_parent_pending,
    isnull(SFDC_data.agileed_personnel_last_sync_c,
    '{{ var("default_date") }}') as SFDC_agileed_personnel_last_sync,
    isnull(SFDC_data.alt_phone_c,
    '{{ var("default_varchar") }}') as SFDC_alt_phone,
    isnull(SFDC_data.cares_act_allocation_c,
    {{ var("default_numeric") }}) as SFDC_cares_act_allocation,
    isnull(SFDC_data.category_c,
    '{{ var("default_varchar") }}') as SFDC_category,
    isnull(SFDC_data.check_national_id_c,
    {{ var("default_boolean") }}) as SFDC_check_national_id,
    isnull(SFDC_data.closed_district_tx_adoption_c,
    {{ var("default_boolean") }}) as SFDC_closed_district_tx_adoption,
    isnull(SFDC_data.code_monkey_customer_c,
    {{ var("default_boolean") }}) as SFDC_code_monkey_customer,
    isnull(SFDC_data.codester_id_c,
    '{{ var("default_varchar") }}') as SFDC_codester_id,
    isnull(SFDC_data.codesters_account_to_be_migrated_to_prod_c,
    {{ var("default_boolean") }}) as SFDC_codesters_account_to_be_migrated_to_prod,
    isnull(SFDC_data.codesters_customer_2_c,
    {{ var("default_boolean") }}) as SFDC_codesters_customer_2,
    isnull(SFDC_data.codesters_customer_dedupe_flag_c,
    {{ var("default_boolean") }}) as SFDC_codesters_customer_dedupe_flag,
    isnull(SFDC_data.company_domain_name_c,
    '{{ var("default_varchar") }}') as SFDC_company_domain_name,
    isnull(SFDC_data.completed_onboarding_c,
    {{ var("default_boolean") }}) as SFDC_completed_onboarding,
    isnull(SFDC_data.computer_os_c,
    '{{ var("default_varchar") }}') as SFDC_computer_os,
    isnull(SFDC_data.contracted_roll_up_c,
    {{ var("default_numeric") }}) as SFDC_contracted_roll_up,
    isnull(SFDC_data.county_name_c,
    '{{ var("default_varchar") }}') as SFDC_county_name,
    isnull(SFDC_data.created_by_id,
    '{{ var("default_varchar") }}') as SFDC_created_by_id,
    isnull(SFDC_data.created_date,
    '{{ var("default_date") }}') as SFDC_created_date,
    isnull(SFDC_data.csm_email_c,
    '{{ var("default_varchar") }}') as SFDC_csm_email,
    isnull(SFDC_data.csm_name_c,
    '{{ var("default_varchar") }}') as SFDC_csm_name,
    isnull(SFDC_data.current_renewal_arr_c,
    {{ var("default_numeric") }}) as SFDC_current_renewal_arr,
    isnull(SFDC_data.current_total_ultimate_parent_c,
    '{{ var("default_varchar") }}') as SFDC_current_total_ultimate_parent,
    isnull(SFDC_data.customer_type_c,
    '{{ var("default_varchar") }}') as SFDC_customer_type,
    isnull(SFDC_data.data_quality_description_c,
    '{{ var("default_varchar") }}') as SFDC_data_quality_description,
    isnull(SFDC_data.data_quality_score_c,
    {{ var("default_numeric") }}) as SFDC_data_quality_score,
    isnull(SFDC_data.de_identified_district_c,
    {{ var("default_boolean") }}) as SFDC_de_identified_district,
    isnull(SFDC_data.description,
    '{{ var("default_varchar") }}') as SFDC_description,
    isnull(SFDC_data.detailed_grade_c,
    '{{ var("default_varchar") }}') as SFDC_detailed_grade,
    isnull(SFDC_data.district_c,
    '{{ var("default_varchar") }}') as SFDC_district,
    isnull(SFDC_data.district_easy_code_tam_c,
    {{ var("default_numeric") }}) as SFDC_district_easy_code_tam,
    isnull(SFDC_data.district_easy_tech_tam_c,
    {{ var("default_numeric") }}) as SFDC_district_easy_tech_tam,
    isnull(SFDC_data.district_elementary_teachers_c,
    '{{ var("default_varchar") }}') as SFDC_district_elementary_teachers,
    isnull(SFDC_data.district_enrollment_c,
    {{ var("default_numeric") }}) as SFDC_district_enrollment,
    isnull(SFDC_data.district_expansion_potential_c,
    {{ var("default_numeric") }}) as SFDC_district_expansion_potential,
    isnull(SFDC_data.district_faculty_library_media_fte_c,
    {{ var("default_numeric") }}) as SFDC_district_faculty_library_media_fte,
    isnull(SFDC_data.district_instructional_expenditures_c,
    '{{ var("default_varchar") }}') as SFDC_district_instructional_expenditures,
    isnull(SFDC_data.district_k_8_enrollment_c,
    {{ var("default_numeric") }}) as SFDC_district_k_8_enrollment,
    isnull(SFDC_data.district_kindergarten_teachers_c,
    '{{ var("default_varchar") }}') as SFDC_district_kindergarten_teachers,
    isnull(SFDC_data.district_local_revenue_cities_c,
    {{ var("default_numeric") }}) as SFDC_district_local_revenue_cities,
    isnull(SFDC_data.district_local_revenue_other_leas_c,
    '{{ var("default_varchar") }}') as SFDC_district_local_revenue_other_leas,
    isnull(SFDC_data.district_local_revenue_other_taxes_c,
    '{{ var("default_varchar") }}') as SFDC_district_local_revenue_other_taxes,
    isnull(SFDC_data.district_local_revenue_property_taxes_c,
    '{{ var("default_varchar") }}') as SFDC_district_local_revenue_property_taxes,
    isnull(SFDC_data.district_nces_c,
    '{{ var("default_varchar") }}') as SFDC_district_nces,
    isnull(SFDC_data.district_presence_c,
    {{ var("default_numeric") }}) as SFDC_district_presence,
    isnull(SFDC_data.district_state_initiative_c,
    {{ var("default_boolean") }}) as SFDC_district_state_initiative,
    isnull(SFDC_data.district_total_capital_outlay_c,
    '{{ var("default_varchar") }}') as SFDC_district_total_capital_outlay,
    isnull(SFDC_data.district_total_expenditures_c,
    '{{ var("default_varchar") }}') as SFDC_district_total_expenditures,
    isnull(SFDC_data.district_total_expense_per_student_c,
    '{{ var("default_varchar") }}') as SFDC_district_total_expense_per_student,
    isnull(SFDC_data.district_total_fed_revenue_c,
    '{{ var("default_varchar") }}') as SFDC_district_total_fed_revenue,
    isnull(SFDC_data.district_total_local_revenue_c,
    '{{ var("default_varchar") }}') as SFDC_district_total_local_revenue,
    isnull(SFDC_data.district_total_revenue_c,
    '{{ var("default_varchar") }}') as SFDC_district_total_revenue,
    isnull(SFDC_data.district_total_state_revenue_c,
    '{{ var("default_varchar") }}') as SFDC_district_total_state_revenue,
    isnull(SFDC_data.district_total_tam_c,
    {{ var("default_numeric") }}) as SFDC_district_total_tam,
    isnull(SFDC_data.district_type_c,
    '{{ var("default_varchar") }}') as SFDC_district_type,
    isnull(SFDC_data.dq_opportunities_c,
    {{ var("default_numeric") }}) as SFDC_dq_opportunities,
    isnull(SFDC_data.easy_tech_customer_c,
    {{ var("default_boolean") }}) as SFDC_easy_tech_customer,
    isnull(SFDC_data.easy_tech_tam_c,
    {{ var("default_numeric") }}) as SFDC_easy_tech_tam,
    isnull(SFDC_data.easy_tech_tam_captured_c,
    {{ var("default_numeric") }}) as SFDC_easy_tech_tam_captured,
    isnull(SFDC_data.ec_tam_c,
    {{ var("default_numeric") }}) as SFDC_ec_tam,
    isnull(SFDC_data.education_climate_index_c,
    {{ var("default_numeric") }}) as SFDC_education_climate_index,
    isnull(SFDC_data.education_type_c,
    '{{ var("default_varchar") }}') as SFDC_education_type,
    isnull(SFDC_data.eighth_grade_enrollment_c,
    {{ var("default_numeric") }}) as SFDC_eighth_grade_enrollment,
    isnull(SFDC_data.email_domain_c,
    '{{ var("default_varchar") }}') as SFDC_email_domain,
    isnull(SFDC_data.enrollment_advanced_placement_c,
    '{{ var("default_varchar") }}') as SFDC_enrollment_advanced_placement,
    isnull(SFDC_data.enrollment_band_c,
    '{{ var("default_varchar") }}') as SFDC_enrollment_band,
    isnull(SFDC_data.enrollment_tier_c,
    '{{ var("default_varchar") }}') as SFDC_enrollment_tier,
    isnull(SFDC_data.esser_funding_c,
    '{{ var("default_varchar") }}') as SFDC_esser_funding,
    isnull(SFDC_data.et_tam_c,
    {{ var("default_numeric") }}) as SFDC_et_tam,
    isnull(SFDC_data.exes_campaign_c,
    {{ var("default_boolean") }}) as SFDC_exes_campaign,
    isnull(SFDC_data.fifth_grade_enrollment_c,
    {{ var("default_numeric") }}) as SFDC_fifth_grade_enrollment,
    isnull(SFDC_data.first_grade_enrollment_c,
    {{ var("default_numeric") }}) as SFDC_first_grade_enrollment,
    isnull(SFDC_data.first_name_c,
    '{{ var("default_varchar") }}') as SFDC_first_name,
    isnull(SFDC_data.fiscal_career_and_tech_federal_c,
    '{{ var("default_varchar") }}') as SFDC_fiscal_career_and_tech_federal,
    isnull(SFDC_data.fiscal_career_and_tech_state_c,
    '{{ var("default_varchar") }}') as SFDC_fiscal_career_and_tech_state,
    isnull(SFDC_data.fiscal_career_and_tech_teacher_salar_c,
    '{{ var("default_varchar") }}') as SFDC_fiscal_career_and_tech_teacher_salar,
    isnull(SFDC_data.fiscal_title_i_eligible_school_c,
    '{{ var("default_varchar") }}') as SFDC_fiscal_title_i_eligible_school,
    isnull(SFDC_data.fiscal_title_i_funding_c,
    {{ var("default_numeric") }}) as SFDC_fiscal_title_i_funding,
    isnull(SFDC_data.fiscal_title_i_percentage_c,
    {{ var("default_numeric") }}) as SFDC_fiscal_title_i_percentage,
    isnull(SFDC_data.fiscal_title_i_school_c,
    '{{ var("default_varchar") }}') as SFDC_fiscal_title_i_school,
    isnull(SFDC_data.fiscal_title_i_school_yes_no_c,
    '{{ var("default_varchar") }}') as SFDC_fiscal_title_i_school_yes_no,
    isnull(SFDC_data.fiscal_title_i_schoolwide_c,
    '{{ var("default_varchar") }}') as SFDC_fiscal_title_i_schoolwide,
    isnull(SFDC_data.fiscal_title_i_schoolwide_yes_no_c,
    '{{ var("default_varchar") }}') as SFDC_fiscal_title_i_schoolwide_yes_no,
    isnull(SFDC_data.free_lunch_students_c,
    '{{ var("default_varchar") }}') as SFDC_free_lunch_students,
    isnull(SFDC_data.free_reduced_lunch_c,
    {{ var("default_numeric") }}) as SFDC_free_reduced_lunch,
    isnull(SFDC_data.gainsight_customer_c,
    {{ var("default_boolean") }}) as SFDC_gainsight_customer,
    isnull(SFDC_data.gainsight_house_c,
    {{ var("default_boolean") }}) as SFDC_gainsight_house,
    isnull(SFDC_data.google_integration_c,
    {{ var("default_boolean") }}) as SFDC_google_integration,
    isnull(SFDC_data.governor_c,
    '{{ var("default_varchar") }}') as SFDC_governor,
    isnull(SFDC_data.governor_s_party_affiliation_c,
    '{{ var("default_varchar") }}') as SFDC_governor_s_party_affiliation,
    isnull(SFDC_data.grade_level_detail_c,
    '{{ var("default_varchar") }}') as SFDC_grade_level_detail,
    isnull(SFDC_data.grade_levels_c,
    '{{ var("default_varchar") }}') as SFDC_grade_levels,
    isnull(SFDC_data.has_codesters_child_accounts_c,
    {{ var("default_boolean") }}) as SFDC_has_codesters_child_accounts,
    isnull(SFDC_data.hi_speed_classroom_internet_c,
    '{{ var("default_varchar") }}') as SFDC_hi_speed_classroom_internet,
    isnull(SFDC_data.hi_speed_internet_c,
    '{{ var("default_varchar") }}') as SFDC_hi_speed_internet,
    isnull(SFDC_data.hml_title_i_funding_c,
    '{{ var("default_varchar") }}') as SFDC_hml_title_i_funding,
    isnull(SFDC_data.hml_title_i_per_student_c,
    '{{ var("default_varchar") }}') as SFDC_hml_title_i_per_student,
    isnull(SFDC_data.house_account_c,
    {{ var("default_boolean") }}) as SFDC_house_account,
    isnull(SFDC_data.i_pad_schools_percent_c,
    {{ var("default_numeric") }}) as SFDC_i_pad_schools_percent,
    isnull(SFDC_data.i_pads_for_instruction_c,
    '{{ var("default_varchar") }}') as SFDC_i_pads_for_instruction,
    isnull(SFDC_data.ima_coordinator_identified_c,
    {{ var("default_boolean") }}) as SFDC_ima_coordinator_identified,
    isnull(SFDC_data.inst_uid_c,
    '{{ var("default_varchar") }}') as SFDC_inst_uid,
    isnull(SFDC_data.k_12_enrollment_c,
    {{ var("default_numeric") }}) as SFDC_k_12_enrollment,
    isnull(SFDC_data.k_5_enrollment_c,
    {{ var("default_numeric") }}) as SFDC_k_5_enrollment,
    isnull(SFDC_data.k_8_district_presence_c,
    {{ var("default_numeric") }}) as SFDC_k_8_district_presence,
    isnull(SFDC_data.k_8_enrollment_c,
    {{ var("default_numeric") }}) as SFDC_k_8_enrollment,
    isnull(SFDC_data.key_account_c,
    {{ var("default_boolean") }}) as SFDC_key_account,
    isnull(SFDC_data.kindergarten_enrollment_c,
    {{ var("default_numeric") }}) as SFDC_kindergarten_enrollment,
    isnull(SFDC_data.known_duplicate_c,
    {{ var("default_boolean") }}) as SFDC_known_duplicate,
    isnull(SFDC_data.last_activity_date,
    '{{ var("default_date") }}') as SFDC_last_activity_date,
    isnull(SFDC_data.last_activity_logged_on_c,
    '{{ var("default_date") }}') as SFDC_last_activity_logged_on,
    isnull(SFDC_data.last_modified_by_id,
    '{{ var("default_varchar") }}') as SFDC_last_modified_by_id,
    isnull(SFDC_data.last_modified_date,
    '{{ var("default_date") }}') as SFDC_last_modified_date,
    isnull(SFDC_data.last_name_c,
    '{{ var("default_varchar") }}') as SFDC_last_name,
    isnull(SFDC_data.lcom_account_c,
    '{{ var("default_varchar") }}') as SFDC_lcom_account,
    isnull(SFDC_data.lcom_account_class_c,
    '{{ var("default_varchar") }}') as SFDC_lcom_account_class,
    isnull(SFDC_data.lcom_account_count_c,
    {{ var("default_numeric") }}) as SFDC_lcom_account_count,
    isnull(SFDC_data.lcom_organization_c,
    '{{ var("default_varchar") }}') as SFDC_lcom_organization,
    isnull(SFDC_data.lcom_organization_count_c,
    {{ var("default_numeric") }}) as SFDC_lcom_organization_count,
    isnull(SFDC_data.lcom_organization_has_parent_c,
    {{ var("default_boolean") }}) as SFDC_lcom_organization_has_parent,
    isnull(SFDC_data.learn_dash_code_sent_c,
    {{ var("default_boolean") }}) as SFDC_learn_dash_code_sent,
    isnull(SFDC_data.les_opp_c,
    {{ var("default_boolean") }}) as SFDC_les_opp,
    isnull(SFDC_data.license_consumption_c,
    {{ var("default_numeric") }}) as SFDC_license_consumption,
    isnull(SFDC_data.map_tracker_c,
    {{ var("default_boolean") }}) as SFDC_map_tracker,
    isnull(SFDC_data.mdr_number_c,
    '{{ var("default_varchar") }}') as SFDC_mdr_number,
    isnull(SFDC_data.mi_pilot_c,
    {{ var("default_boolean") }}) as SFDC_mi_pilot,
    isnull(SFDC_data.multi_tiered_account_c,
    {{ var("default_boolean") }}) as SFDC_multi_tiered_account,
    isnull(SFDC_data.name_with_lcom_organization_info_c,
    '{{ var("default_varchar") }}') as SFDC_name_with_lcom_organization_info,
    isnull(SFDC_data.national_district_id_c,
    '{{ var("default_varchar") }}') as SFDC_national_district_id,
    isnull(SFDC_data.national_school_id_c,
    '{{ var("default_varchar") }}') as SFDC_national_school_id,
    isnull(SFDC_data.nc_tier_1_c,
    {{ var("default_boolean") }}) as SFDC_nc_tier_1,
    isnull(SFDC_data.nces_lea_id_c,
    '{{ var("default_varchar") }}') as SFDC_nces_lea_id,
    isnull(SFDC_data.nces_unique_id_c,
    '{{ var("default_varchar") }}') as SFDC_nces_unique_id,
    isnull(SFDC_data.net_suite_id_c,
    '{{ var("default_varchar") }}') as SFDC_net_suite_id,
    isnull(SFDC_data.net_suite_link_c,
    '{{ var("default_varchar") }}') as SFDC_net_suite_link,
    isnull(SFDC_data.netsuite_account_number_c,
    '{{ var("default_varchar") }}') as SFDC_netsuite_account_number,
    isnull(SFDC_data.no_of_child_account_c,
    {{ var("default_numeric") }}) as SFDC_no_of_child_account,
    isnull(SFDC_data.nps_count_c,
    {{ var("default_numeric") }}) as SFDC_nps_count,
    isnull(SFDC_data.nps_score_c,
    {{ var("default_numeric") }}) as SFDC_nps_score,
    isnull(SFDC_data.nps_sum_c,
    {{ var("default_numeric") }}) as SFDC_nps_sum,
    isnull(SFDC_data.num_opps_c,
    {{ var("default_numeric") }}) as SFDC_num_opps,
    isnull(SFDC_data.number_of_2020_opps_c,
    {{ var("default_numeric") }}) as SFDC_number_of_2020_opps,
    isnull(SFDC_data.number_of_active_easy_tech_subscriptions_c,
    {{ var("default_numeric") }}) as SFDC_number_of_active_easy_tech_subscriptions,
    isnull(SFDC_data.number_of_active_vidcode_subscriptions_c,
    {{ var("default_numeric") }}) as SFDC_number_of_active_vidcode_subscriptions,
    isnull(SFDC_data.number_of_elementary_schools_c,
    {{ var("default_numeric") }}) as SFDC_number_of_elementary_schools,
    isnull(SFDC_data.number_of_high_schools_c,
    {{ var("default_numeric") }}) as SFDC_number_of_high_schools,
    isnull(SFDC_data.number_of_k_8_buildings_c,
    {{ var("default_numeric") }}) as SFDC_number_of_k_8_buildings,
    isnull(SFDC_data.number_of_middle_schools_c,
    {{ var("default_numeric") }}) as SFDC_number_of_middle_schools,
    isnull(SFDC_data.number_of_open_opportunities_c,
    {{ var("default_numeric") }}) as SFDC_number_of_open_opportunities,
    isnull(SFDC_data.number_of_open_opps_c,
    {{ var("default_numeric") }}) as SFDC_number_of_open_opps,
    isnull(SFDC_data.number_of_page_views_c,
    {{ var("default_numeric") }}) as SFDC_number_of_page_views,
    isnull(SFDC_data.number_of_renewal_opps_c,
    {{ var("default_numeric") }}) as SFDC_number_of_renewal_opps,
    isnull(SFDC_data.number_of_schools_c,
    {{ var("default_numeric") }}) as SFDC_number_of_schools,
    isnull(SFDC_data.number_of_sessions_c,
    {{ var("default_numeric") }}) as SFDC_number_of_sessions,
    isnull(SFDC_data.number_of_title_i_schools_c,
    {{ var("default_numeric") }}) as SFDC_number_of_title_i_schools,
    isnull(SFDC_data.number_of_won_renewal_opportunities_c,
    {{ var("default_numeric") }}) as SFDC_number_of_won_renewal_opportunities,
    isnull(SFDC_data.open_opportunity_amount_c,
    {{ var("default_numeric") }}) as SFDC_open_opportunity_amount,
    isnull(SFDC_data.open_renewal_opportunities_c,
    {{ var("default_numeric") }}) as SFDC_open_renewal_opportunities,
    isnull(SFDC_data.org_type_c,
    '{{ var("default_varchar") }}') as SFDC_org_type,
    isnull(SFDC_data.otc_provisioned_c,
    {{ var("default_boolean") }}) as SFDC_otc_provisioned,
    isnull(SFDC_data.owner_c,
    '{{ var("default_varchar") }}') as SFDC_owner,
    isnull(SFDC_data.owner_id,
    '{{ var("default_varchar") }}') as SFDC_owner_id,
    isnull(SFDC_data.owner_name_text_c,
    '{{ var("default_varchar") }}') as SFDC_owner_name_text,
    isnull(SFDC_data.parent_account_owner_c,
    '{{ var("default_varchar") }}') as SFDC_parent_account_owner,
    isnull(SFDC_data.parent_and_child_match_c,
    {{ var("default_numeric") }}) as SFDC_parent_and_child_match,
    isnull(SFDC_data.parent_churned_c,
    {{ var("default_boolean") }}) as SFDC_parent_churned,
    isnull(SFDC_data.parent_et_tam_c,
    {{ var("default_numeric") }}) as SFDC_parent_et_tam,
    isnull(SFDC_data.parent_gsid_c,
    '{{ var("default_varchar") }}') as SFDC_parent_gsid,
    isnull(SFDC_data.parent_id,
    '{{ var("default_varchar") }}') as SFDC_parent_id,
    isnull(SFDC_data.parent_long_name_c,
    '{{ var("default_varchar") }}') as SFDC_parent_long_name,
    isnull(SFDC_data.parent_mdr_c,
    '{{ var("default_varchar") }}') as SFDC_parent_mdr,
    isnull(SFDC_data.parent_name_c,
    '{{ var("default_varchar") }}') as SFDC_parent_name,
    isnull(SFDC_data.parent_name_proper_case_c,
    '{{ var("default_varchar") }}') as SFDC_parent_name_proper_case,
    isnull(SFDC_data.parent_owner_id_c,
    '{{ var("default_varchar") }}') as SFDC_parent_owner_id,
    isnull(SFDC_data.parent_uid_c,
    '{{ var("default_varchar") }}') as SFDC_parent_uid,
    isnull(SFDC_data.pct_afro_amer_c,
    {{ var("default_numeric") }}) as SFDC_pct_afro_amer,
    isnull(SFDC_data.pct_asian_c,
    {{ var("default_numeric") }}) as SFDC_pct_asian,
    isnull(SFDC_data.pct_hisp_c,
    {{ var("default_numeric") }}) as SFDC_pct_hisp,
    isnull(SFDC_data.pct_multi_racial_c,
    {{ var("default_numeric") }}) as SFDC_pct_multi_racial,
    isnull(SFDC_data.pct_native_c,
    {{ var("default_numeric") }}) as SFDC_pct_native,
    isnull(SFDC_data.pct_white_c,
    {{ var("default_numeric") }}) as SFDC_pct_white,
    isnull(SFDC_data.per_student_expenditures_c,
    '{{ var("default_varchar") }}') as SFDC_per_student_expenditures,
    isnull(SFDC_data.percent_students_ell_c,
    {{ var("default_numeric") }}) as SFDC_percent_students_ell,
    isnull(SFDC_data.phone,
    '{{ var("default_varchar") }}') as SFDC_phone,
    isnull(SFDC_data.photo_url,
    '{{ var("default_varchar") }}') as SFDC_photo_url,
    isnull(SFDC_data.platform_sync_c,
    {{ var("default_boolean") }}) as SFDC_platform_sync,
    isnull(SFDC_data.poverty_percent_under_age_18_c,
    {{ var("default_numeric") }}) as SFDC_poverty_percent_under_age_18,
    isnull(SFDC_data.pre_k_enrollment_c,
    {{ var("default_numeric") }}) as SFDC_pre_k_enrollment,
    isnull(SFDC_data.priority_account_c,
    {{ var("default_boolean") }}) as SFDC_priority_account,
    isnull(SFDC_data.record_type_c,
    '{{ var("default_varchar") }}') as SFDC_record_type,
    isnull(SFDC_data.reduced_lunch_student_c,
    {{ var("default_numeric") }}) as SFDC_reduced_lunch_student,
    isnull(SFDC_data.reference_customer_c,
    {{ var("default_boolean") }}) as SFDC_reference_customer,
    isnull(SFDC_data.related_activity_c,
    '{{ var("default_varchar") }}') as SFDC_related_activity,
    isnull(SFDC_data.related_c,
    {{ var("default_boolean") }}) as SFDC_related,
    isnull(SFDC_data.renewal_forecast_segment_c,
    '{{ var("default_varchar") }}') as SFDC_renewal_forecast_segment,
    isnull(SFDC_data.resa_name_proper_c,
    '{{ var("default_varchar") }}') as SFDC_resa_name_proper,
    isnull(SFDC_data.resa_uid_c,
    {{ var("default_numeric") }}) as SFDC_resa_uid,
    isnull(SFDC_data.sales_owner_field_c,
    '{{ var("default_varchar") }}') as SFDC_sales_owner_field,
    isnull(SFDC_data.sales_support_rep_c,
    '{{ var("default_varchar") }}') as SFDC_sales_support_rep,
    isnull(SFDC_data.sbqq_co_termed_contracts_combined_c,
    {{ var("default_boolean") }}) as SFDC_sbqq_co_termed_contracts_combined,
    isnull(SFDC_data.sbqq_contract_co_termination_c,
    '{{ var("default_varchar") }}') as SFDC_sbqq_contract_co_termination,
    isnull(SFDC_data.sbqq_preserve_bundle_c,
    {{ var("default_boolean") }}) as SFDC_sbqq_preserve_bundle,
    isnull(SFDC_data.school_enrollment_c,
    {{ var("default_numeric") }}) as SFDC_school_enrollment,
    isnull(SFDC_data.school_id_c,
    '{{ var("default_varchar") }}') as SFDC_school_id,
    isnull(SFDC_data.school_type_c,
    '{{ var("default_varchar") }}') as SFDC_school_type,
    isnull(SFDC_data.school_year_end_c,
    '{{ var("default_date") }}') as SFDC_school_year_end,
    isnull(SFDC_data.school_year_start_c,
    '{{ var("default_date") }}') as SFDC_school_year_start,
    isnull(SFDC_data.schools_in_district_c,
    {{ var("default_numeric") }}) as SFDC_schools_in_district,
    isnull(SFDC_data.state_eligible_or_initiative_c,
    {{ var("default_boolean") }}) as SFDC_state_eligible_or_initiative,
    isnull(SFDC_data.state_initiative_c,
    {{ var("default_boolean") }}) as SFDC_state_initiative,
    isnull(SFDC_data.state_profile_c,
    '{{ var("default_varchar") }}') as SFDC_state_profile,
    isnull(SFDC_data.state_program_eligible_c,
    {{ var("default_boolean") }}) as SFDC_state_program_eligible,
    isnull(SFDC_data.student_tam_c,
    {{ var("default_numeric") }}) as SFDC_student_tam,
    isnull(SFDC_data.sync_district_c,
    {{ var("default_boolean") }}) as SFDC_sync_district,
    isnull(SFDC_data.syncing_district_c,
    {{ var("default_boolean") }}) as SFDC_syncing_district,
    isnull(SFDC_data.system_modstamp,
    '{{ var("default_date") }}') as SFDC_system_modstamp,
    isnull(SFDC_data.target_account_c,
    {{ var("default_boolean") }}) as SFDC_target_account,
    isnull(SFDC_data.teachers_in_building_c,
    {{ var("default_numeric") }}) as SFDC_teachers_in_building,
    isnull(SFDC_data.technology_equipment_c,
    '{{ var("default_varchar") }}') as SFDC_technology_equipment,
    isnull(SFDC_data.technology_index_c,
    {{ var("default_numeric") }}) as SFDC_technology_index,
    isnull(SFDC_data.technology_measure_c,
    '{{ var("default_varchar") }}') as SFDC_technology_measure,
    isnull(SFDC_data.technology_supplies_and_purchases_c,
    '{{ var("default_varchar") }}') as SFDC_technology_supplies_and_purchases,
    isnull(SFDC_data.territory_c,
    '{{ var("default_varchar") }}') as SFDC_territory,
    isnull(SFDC_data.territory_list_c,
    '{{ var("default_varchar") }}') as SFDC_territory_list,
    isnull(SFDC_data.test_account_c,
    {{ var("default_boolean") }}) as SFDC_test_account,
    isnull(SFDC_data.tiered_service_level_c,
    '{{ var("default_varchar") }}') as SFDC_tiered_service_level,
    isnull(SFDC_data.time_zone_c,
    {{ var("default_numeric") }}) as SFDC_time_zone,
    isnull(SFDC_data.time_zone_raw_c,
    {{ var("default_numeric") }}) as SFDC_time_zone_raw,
    isnull(SFDC_data.time_zone_transformed_c,
    '{{ var("default_varchar") }}') as SFDC_time_zone_transformed,
    isnull(SFDC_data.title_iv_funding_21_st_century_grants_c,
    '{{ var("default_varchar") }}') as SFDC_title_iv_funding_21_st_century_grants,
    isnull(SFDC_data.title_iv_funding_student_support_c,
    '{{ var("default_varchar") }}') as SFDC_title_iv_funding_student_support,
    isnull(SFDC_data.top_75_account_c,
    {{ var("default_boolean") }}) as SFDC_top_75_account,
    isnull(SFDC_data.total_credits_purchased_c,
    {{ var("default_numeric") }}) as SFDC_total_credits_purchased,
    isnull(SFDC_data.total_number_of_schools_c,
    {{ var("default_numeric") }}) as SFDC_total_number_of_schools,
    isnull(SFDC_data.total_renewal_arr_c,
    {{ var("default_numeric") }}) as SFDC_total_renewal_arr,
    isnull(SFDC_data.trend_district_revenue_c,
    '{{ var("default_varchar") }}') as SFDC_trend_district_revenue,
    isnull(SFDC_data.trend_enrollment_c,
    '{{ var("default_varchar") }}') as SFDC_trend_enrollment,
    isnull(SFDC_data.trend_federal_revenue_c,
    '{{ var("default_varchar") }}') as SFDC_trend_federal_revenue,
    isnull(SFDC_data.trend_instructional_expenditures_c,
    '{{ var("default_varchar") }}') as SFDC_trend_instructional_expenditures,
    isnull(SFDC_data.trend_local_revenue_c,
    '{{ var("default_varchar") }}') as SFDC_trend_local_revenue,
    isnull(SFDC_data.trend_state_revenue_c,
    '{{ var("default_varchar") }}') as SFDC_trend_state_revenue,
    isnull(SFDC_data.trend_title_i_revenue_c,
    '{{ var("default_varchar") }}') as SFDC_trend_title_i_revenue,
    isnull(SFDC_data.type,
    '{{ var("default_varchar") }}') as SFDC_type,
    isnull(SFDC_data.ultimate_account_lifecycle_stage_c,
    '{{ var("default_varchar") }}') as SFDC_ultimate_account_lifecycle_stage,
    isnull(SFDC_data.ultimate_account_owner_c,
    '{{ var("default_varchar") }}') as SFDC_ultimate_account_owner,
    isnull(SFDC_data.ultimate_parent_account_c,
    '{{ var("default_varchar") }}') as SFDC_ultimate_parent_account,
    isnull(SFDC_data.ultimate_parent_billing_state_c,
    '{{ var("default_varchar") }}') as SFDC_ultimate_parent_billing_state,
    isnull(SFDC_data.ultimate_parent_id_c,
    '{{ var("default_varchar") }}') as SFDC_ultimate_parent_id,
    isnull(SFDC_data.ultimate_parent_total_renewal_arr_2_c,
    {{ var("default_numeric") }}) as SFDC_ultimate_parent_total_renewal_arr_2,
    isnull(SFDC_data.urban_rural_c,
    '{{ var("default_varchar") }}') as SFDC_urban_rural,
    isnull(SFDC_data.vidcode_customer_2_c,
    {{ var("default_boolean") }}) as SFDC_vidcode_customer_2,
    isnull(SFDC_data.virtual_school_c,
    '{{ var("default_varchar") }}') as SFDC_virtual_school,
    isnull(SFDC_data.virtual_status_text_c,
    '{{ var("default_varchar") }}') as SFDC_virtual_status_text,
    isnull(SFDC_data.website,
    '{{ var("default_varchar") }}') as SFDC_website,
    isnull(SFDC_data.x_1_1_computing_c,
    '{{ var("default_varchar") }}') as SFDC_x_1_1_computing,
    isnull(SFDC_data.x_10_th_grade_enrollment_c,
    {{ var("default_numeric") }}) as SFDC_x_10_th_grade_enrollment,
    isnull(SFDC_data.x_11_th_grade_enrollment_c,
    {{ var("default_numeric") }}) as SFDC_x_11_th_grade_enrollment,
    isnull(SFDC_data.x_12_th_grade_enrollment_c,
    {{ var("default_numeric") }}) as SFDC_x_12_th_grade_enrollment,
    isnull(SFDC_data.x_2_nd_grade_enrollment_c,
    {{ var("default_numeric") }}) as SFDC_x_2_nd_grade_enrollment,
    isnull(SFDC_data.x_2020_service_purchased_c,
    {{ var("default_boolean") }}) as SFDC_x_2020_service_purchased,
    isnull(SFDC_data.x_21_csa_eol_c,
    {{ var("default_boolean") }}) as SFDC_x_21_csa_eol,
    isnull(SFDC_data.x_3_plms_c,
    {{ var("default_boolean") }}) as SFDC_x_3_plms,
    isnull(SFDC_data.x_3_rd_grade_enrollment_c,
    {{ var("default_numeric") }}) as SFDC_x_3_rd_grade_enrollment,
    isnull(SFDC_data.x_4_th_grade_enrollment_c,
    {{ var("default_numeric") }}) as SFDC_x_4_th_grade_enrollment,
    isnull(SFDC_data.x_6_th_grade_enrollment_c,
    {{ var("default_numeric") }}) as SFDC_x_6_th_grade_enrollment,
    isnull(SFDC_data.x_7_th_grade_enrollment_c,
    {{ var("default_numeric") }}) as SFDC_x_7_th_grade_enrollment,
    isnull(SFDC_data.x_9_th_grade_enrollment_c,
    {{ var("default_numeric") }}) as SFDC_x_9_th_grade_enrollment,
    isnull(SFDC_data.zendesk_domain_c,
    '{{ var("default_varchar") }}') as SFDC_zendesk_domain,
    isnull(SFDC_data.lcom_organization_id,
    '{{ var("default_varchar") }}') as  SFDC_lcom_organization_id,
    --School (some child accounts info)
isnull(SFDC_data.state_initiative_school,
    {{ var("default_boolean") }}) as SFDC_state_initiative_school,
    isnull(SFDC_data.district_state_initiative_school,
    {{ var("default_boolean") }}) as SFDC_district_state_initiative_school,
    isnull(SFDC_data.state_eligible_or_initiative_school,
    {{ var("default_boolean") }}) as SFDC_state_eligible_or_initiative_school,
    --District (some parent account info)
isnull(SFDC_data.state_initiative_district,
    {{ var("default_boolean") }}) as SFDC_state_initiative_district,
    isnull(SFDC_data.district_state_initiative_district,
    {{ var("default_boolean") }}) as SFDC_district_state_initiative_district,
    isnull(SFDC_data.state_eligible_or_initiative_district,
    {{ var("default_boolean") }}) as SFDC_state_eligible_or_initiative_district,
    --Calculated
--
case when
(
 SFDC_data.grade_levels_c = 'High School'
or
(SFDC_data.grade_levels_c is null and  SFDC_data.k_12_enrollment_c>0 and SFDC_data.k_8_enrollment_c=0)
) then True
else False
end as isHighSchool
--
--
FROM LCOM_data
--
full outer join SFDC_data
on LCOM_data.salesforce_id = SFDC_data.Id


/*add default values for the first run only*/

union all
/*default*/
select 
--LCOM columns
'{{ var("default_ID") }}' as account_id,
'{{ var("default_ID") }}' as lcom_organization_id,
'{{ var("default_varchar") }}' as  lcom_organization_name,
'{{ var("default_varchar") }}' as  lcom_organization_type,
'{{ var("default_ID") }}' as  lcom_parent_organization_id,
'{{ var("default_varchar") }}' as  lcom_parent_organization_name,
{{ var("default_boolean") }} as  lcom_trial,
{{ var("default_boolean") }} as  lcom_demo,
'{{ var("default_varchar") }}' as  lcom_postal_code,
'{{ var("default_varchar") }}' as  lcom_state_province_key,
'{{ var("default_varchar") }}' as  lcom_state_province_code,
'{{ var("default_varchar") }}' as  lcom_state_province_name,
'{{ var("default_varchar") }}' as  lcom_country_code,
'{{ var("default_varchar") }}' as  lcom_country_name,
'{{ var("default_varchar") }}' as  lcom_alpha3_code,
'{{ var("default_varchar") }}' as  lcom_numeric_code,
'{{ var("default_varchar") }}' as  lcom_external_sis_id,
'{{ var("default_varchar") }}' as  lcom_nces_id,
'{{ var("default_date") }}' lcom_created_datetime,
'{{ var("default_date") }}' lcom_modified_datetime,
'{{ var("default_date") }}' lcom_deleted_datetime,
--SFDC columns
 '{{ var("default_varchar") }}' as SFDC_account_id,
 '{{ var("default_varchar") }}' as SFDC_name,
 '{{ var("default_date") }}' as SFDC_account_last_activity_date ,
  '{{ var("default_varchar") }}' as SFDC_account_lifecycle_stage ,
  '{{ var("default_varchar") }}' as SFDC_account_management_type ,
  '{{ var("default_varchar") }}' as SFDC_act_id ,
   {{ var("default_boolean") }}   as   SFDC_actively_prospecting ,
  '{{ var("default_varchar") }}' as SFDC_activity_metric_id ,
  '{{ var("default_varchar") }}' as SFDC_activity_metric_rollup_id ,
  '{{ var("default_varchar") }}' as SFDC_ae_or_isr ,
  '{{ var("default_varchar") }}' as SFDC_agile_id ,
  '{{ var("default_varchar") }}' as SFDC_agile_lms ,
   {{ var("default_boolean") }}   as   SFDC_agileed_agile_ed_insert ,
  '{{ var("default_varchar") }}' as SFDC_agileed_agile_ed_key ,
  '{{ var("default_date") }}' as SFDC_agileed_agile_ed_latest_update_date ,
  '{{ var("default_varchar") }}' as SFDC_agileed_agile_ed_parent_key ,
  '{{ var("default_varchar") }}' as SFDC_agileed_agile_ed_status ,
   {{ var("default_boolean") }}   as   SFDC_agileed_agile_ed_up_to_date ,
   {{ var("default_boolean") }}   as   SFDC_agileed_agileed_do_not_update ,
   {{ var("default_numeric") }}   as   SFDC_agileed_connect_link_changed_personnel_titles ,
  '{{ var("default_varchar") }}' as SFDC_agileed_connect_link_district_key ,
  '{{ var("default_varchar") }}' as SFDC_agileed_connect_link_file_type ,
   {{ var("default_numeric") }}   as   SFDC_agileed_connect_link_hierarchized_personnel ,
  '{{ var("default_varchar") }}' as SFDC_agileed_connect_link_licensed_status ,
   {{ var("default_numeric") }}   as   SFDC_agileed_connect_link_personnel_roles ,
   {{ var("default_numeric") }}   as   SFDC_agileed_connect_link_personnel_titles ,
  '{{ var("default_date") }}' as SFDC_agileed_last_sync ,
   {{ var("default_boolean") }}   as   SFDC_agileed_parent_pending ,
  '{{ var("default_date") }}' as SFDC_agileed_personnel_last_sync ,
  '{{ var("default_varchar") }}' as SFDC_alt_phone ,
   {{ var("default_numeric") }}   as   SFDC_cares_act_allocation ,
  '{{ var("default_varchar") }}' as SFDC_category ,
   {{ var("default_boolean") }}   as   SFDC_check_national_id ,
   {{ var("default_boolean") }}   as   SFDC_closed_district_tx_adoption ,
   {{ var("default_boolean") }}   as   SFDC_code_monkey_customer ,
  '{{ var("default_varchar") }}' as SFDC_codester_id ,
   {{ var("default_boolean") }}   as   SFDC_codesters_account_to_be_migrated_to_prod ,
   {{ var("default_boolean") }}   as   SFDC_codesters_customer_2 ,
   {{ var("default_boolean") }}   as   SFDC_codesters_customer_dedupe_flag ,
  '{{ var("default_varchar") }}' as SFDC_company_domain_name ,
   {{ var("default_boolean") }}   as   SFDC_completed_onboarding ,
  '{{ var("default_varchar") }}' as SFDC_computer_os ,
   {{ var("default_numeric") }}   as   SFDC_contracted_roll_up ,
  '{{ var("default_varchar") }}' as SFDC_county_name ,
  '{{ var("default_varchar") }}' as SFDC_created_by_id ,
  '{{ var("default_date") }}' as SFDC_created_date ,
  '{{ var("default_varchar") }}' as SFDC_csm_email ,
  '{{ var("default_varchar") }}' as SFDC_csm_name ,
   {{ var("default_numeric") }}   as   SFDC_current_renewal_arr ,
  '{{ var("default_varchar") }}' as SFDC_current_total_ultimate_parent ,
  '{{ var("default_varchar") }}' as SFDC_customer_type ,
  '{{ var("default_varchar") }}' as SFDC_data_quality_description ,
   {{ var("default_numeric") }}   as   SFDC_data_quality_score ,
   {{ var("default_boolean") }}   as   SFDC_de_identified_district ,
  '{{ var("default_varchar") }}' as SFDC_description ,
  '{{ var("default_varchar") }}' as SFDC_detailed_grade ,
  '{{ var("default_varchar") }}' as SFDC_district ,
   {{ var("default_numeric") }}   as   SFDC_district_easy_code_tam ,
   {{ var("default_numeric") }}   as   SFDC_district_easy_tech_tam ,
  '{{ var("default_varchar") }}' as SFDC_district_elementary_teachers ,
   {{ var("default_numeric") }}   as   SFDC_district_enrollment ,
   {{ var("default_numeric") }}   as   SFDC_district_expansion_potential ,
   {{ var("default_numeric") }}   as   SFDC_district_faculty_library_media_fte ,
  '{{ var("default_varchar") }}' as SFDC_district_instructional_expenditures ,
   {{ var("default_numeric") }}   as   SFDC_district_k_8_enrollment ,
  '{{ var("default_varchar") }}' as SFDC_district_kindergarten_teachers ,
   {{ var("default_numeric") }}   as   SFDC_district_local_revenue_cities ,
  '{{ var("default_varchar") }}' as SFDC_district_local_revenue_other_leas ,
  '{{ var("default_varchar") }}' as SFDC_district_local_revenue_other_taxes ,
  '{{ var("default_varchar") }}' as SFDC_district_local_revenue_property_taxes ,
  '{{ var("default_varchar") }}' as SFDC_district_nces ,
   {{ var("default_numeric") }}   as   SFDC_district_presence ,
   {{ var("default_boolean") }}   as   SFDC_district_state_initiative ,
  '{{ var("default_varchar") }}' as SFDC_district_total_capital_outlay ,
  '{{ var("default_varchar") }}' as SFDC_district_total_expenditures ,
  '{{ var("default_varchar") }}' as SFDC_district_total_expense_per_student ,
  '{{ var("default_varchar") }}' as SFDC_district_total_fed_revenue ,
  '{{ var("default_varchar") }}' as SFDC_district_total_local_revenue ,
  '{{ var("default_varchar") }}' as SFDC_district_total_revenue ,
  '{{ var("default_varchar") }}' as SFDC_district_total_state_revenue ,
   {{ var("default_numeric") }}   as   SFDC_district_total_tam ,
  '{{ var("default_varchar") }}' as SFDC_district_type ,
   {{ var("default_numeric") }}   as   SFDC_dq_opportunities ,
   {{ var("default_boolean") }}   as   SFDC_easy_tech_customer ,
   {{ var("default_numeric") }}   as   SFDC_easy_tech_tam ,
   {{ var("default_numeric") }}   as   SFDC_easy_tech_tam_captured ,
   {{ var("default_numeric") }}   as   SFDC_ec_tam ,
   {{ var("default_numeric") }}   as   SFDC_education_climate_index ,
  '{{ var("default_varchar") }}' as SFDC_education_type ,
   {{ var("default_numeric") }}   as   SFDC_eighth_grade_enrollment ,
  '{{ var("default_varchar") }}' as SFDC_email_domain ,
  '{{ var("default_varchar") }}' as SFDC_enrollment_advanced_placement ,
  '{{ var("default_varchar") }}' as SFDC_enrollment_band ,
  '{{ var("default_varchar") }}' as SFDC_enrollment_tier ,
  '{{ var("default_varchar") }}' as SFDC_esser_funding ,
   {{ var("default_numeric") }}   as   SFDC_et_tam ,
   {{ var("default_boolean") }}   as   SFDC_exes_campaign ,
   {{ var("default_numeric") }}   as   SFDC_fifth_grade_enrollment ,
   {{ var("default_numeric") }}   as   SFDC_first_grade_enrollment ,
  '{{ var("default_varchar") }}' as SFDC_first_name ,
  '{{ var("default_varchar") }}' as SFDC_fiscal_career_and_tech_federal ,
  '{{ var("default_varchar") }}' as SFDC_fiscal_career_and_tech_state ,
  '{{ var("default_varchar") }}' as SFDC_fiscal_career_and_tech_teacher_salar ,
  '{{ var("default_varchar") }}' as SFDC_fiscal_title_i_eligible_school ,
   {{ var("default_numeric") }}   as   SFDC_fiscal_title_i_funding ,
   {{ var("default_numeric") }}   as   SFDC_fiscal_title_i_percentage ,
  '{{ var("default_varchar") }}' as SFDC_fiscal_title_i_school ,
  '{{ var("default_varchar") }}' as SFDC_fiscal_title_i_school_yes_no ,
  '{{ var("default_varchar") }}' as SFDC_fiscal_title_i_schoolwide ,
  '{{ var("default_varchar") }}' as SFDC_fiscal_title_i_schoolwide_yes_no ,
  '{{ var("default_varchar") }}' as SFDC_free_lunch_students ,
   {{ var("default_numeric") }}   as   SFDC_free_reduced_lunch ,
   {{ var("default_boolean") }}   as   SFDC_gainsight_customer ,
   {{ var("default_boolean") }}   as   SFDC_gainsight_house ,
   {{ var("default_boolean") }}   as   SFDC_google_integration ,
  '{{ var("default_varchar") }}' as SFDC_governor ,
  '{{ var("default_varchar") }}' as SFDC_governor_s_party_affiliation ,
  '{{ var("default_varchar") }}' as SFDC_grade_level_detail ,
  '{{ var("default_varchar") }}' as SFDC_grade_levels ,
   {{ var("default_boolean") }}   as   SFDC_has_codesters_child_accounts ,
  '{{ var("default_varchar") }}' as SFDC_hi_speed_classroom_internet ,
  '{{ var("default_varchar") }}' as SFDC_hi_speed_internet ,
  '{{ var("default_varchar") }}' as SFDC_hml_title_i_funding ,
  '{{ var("default_varchar") }}' as SFDC_hml_title_i_per_student ,
   {{ var("default_boolean") }}   as   SFDC_house_account ,
   {{ var("default_numeric") }}   as   SFDC_i_pad_schools_percent ,
  '{{ var("default_varchar") }}' as SFDC_i_pads_for_instruction ,
   {{ var("default_boolean") }}   as   SFDC_ima_coordinator_identified ,
  '{{ var("default_varchar") }}' as SFDC_inst_uid ,
   {{ var("default_numeric") }}   as   SFDC_k_12_enrollment ,
   {{ var("default_numeric") }}   as   SFDC_k_5_enrollment ,
   {{ var("default_numeric") }}   as   SFDC_k_8_district_presence ,
   {{ var("default_numeric") }}   as   SFDC_k_8_enrollment ,
   {{ var("default_boolean") }}   as   SFDC_key_account ,
   {{ var("default_numeric") }}   as   SFDC_kindergarten_enrollment ,
   {{ var("default_boolean") }}   as   SFDC_known_duplicate ,
  '{{ var("default_date") }}' as SFDC_last_activity_date ,
  '{{ var("default_date") }}' as SFDC_last_activity_logged_on ,
  '{{ var("default_varchar") }}' as SFDC_last_modified_by_id ,
  '{{ var("default_date") }}' as SFDC_last_modified_date ,
  '{{ var("default_varchar") }}' as SFDC_last_name ,
  '{{ var("default_varchar") }}' as SFDC_lcom_account ,
  '{{ var("default_varchar") }}' as SFDC_lcom_account_class ,
   {{ var("default_numeric") }}   as   SFDC_lcom_account_count ,
  '{{ var("default_varchar") }}' as SFDC_lcom_organization ,
   {{ var("default_numeric") }}   as   SFDC_lcom_organization_count ,
   {{ var("default_boolean") }}   as   SFDC_lcom_organization_has_parent ,
   {{ var("default_boolean") }}   as   SFDC_learn_dash_code_sent ,
   {{ var("default_boolean") }}   as   SFDC_les_opp ,
   {{ var("default_numeric") }}   as   SFDC_license_consumption ,
   {{ var("default_boolean") }}   as   SFDC_map_tracker ,
  '{{ var("default_varchar") }}' as SFDC_mdr_number ,
   {{ var("default_boolean") }}   as   SFDC_mi_pilot ,
   {{ var("default_boolean") }}   as   SFDC_multi_tiered_account ,
  '{{ var("default_varchar") }}' as SFDC_name_with_lcom_organization_info ,
  '{{ var("default_varchar") }}' as SFDC_national_district_id ,
  '{{ var("default_varchar") }}' as SFDC_national_school_id ,
   {{ var("default_boolean") }}   as   SFDC_nc_tier_1 ,
  '{{ var("default_varchar") }}' as SFDC_nces_lea_id ,
  '{{ var("default_varchar") }}' as SFDC_nces_unique_id ,
  '{{ var("default_varchar") }}' as SFDC_net_suite_id ,
  '{{ var("default_varchar") }}' as SFDC_net_suite_link ,
  '{{ var("default_varchar") }}' as SFDC_netsuite_account_number ,
   {{ var("default_numeric") }}   as   SFDC_no_of_child_account ,
   {{ var("default_numeric") }}   as   SFDC_nps_count ,
   {{ var("default_numeric") }}   as   SFDC_nps_score ,
   {{ var("default_numeric") }}   as   SFDC_nps_sum ,
   {{ var("default_numeric") }}   as   SFDC_num_opps ,
   {{ var("default_numeric") }}   as   SFDC_number_of_2020_opps ,
   {{ var("default_numeric") }}   as   SFDC_number_of_active_easy_tech_subscriptions ,
   {{ var("default_numeric") }}   as   SFDC_number_of_active_vidcode_subscriptions ,
   {{ var("default_numeric") }}   as   SFDC_number_of_elementary_schools ,
   {{ var("default_numeric") }}   as   SFDC_number_of_high_schools ,
   {{ var("default_numeric") }}   as   SFDC_number_of_k_8_buildings ,
   {{ var("default_numeric") }}   as   SFDC_number_of_middle_schools ,
   {{ var("default_numeric") }}   as   SFDC_number_of_open_opportunities ,
   {{ var("default_numeric") }}   as   SFDC_number_of_open_opps ,
   {{ var("default_numeric") }}   as   SFDC_number_of_page_views ,
   {{ var("default_numeric") }}   as   SFDC_number_of_renewal_opps ,
   {{ var("default_numeric") }}   as   SFDC_number_of_schools ,
   {{ var("default_numeric") }}   as   SFDC_number_of_sessions ,
   {{ var("default_numeric") }}   as   SFDC_number_of_title_i_schools ,
   {{ var("default_numeric") }}   as   SFDC_number_of_won_renewal_opportunities ,
   {{ var("default_numeric") }}   as   SFDC_open_opportunity_amount ,
   {{ var("default_numeric") }}   as   SFDC_open_renewal_opportunities ,
  '{{ var("default_varchar") }}' as SFDC_org_type ,
   {{ var("default_boolean") }}   as   SFDC_otc_provisioned ,
  '{{ var("default_varchar") }}' as SFDC_owner ,
  '{{ var("default_varchar") }}' as SFDC_owner_id ,
  '{{ var("default_varchar") }}' as SFDC_owner_name_text ,
  '{{ var("default_varchar") }}' as SFDC_parent_account_owner ,
   {{ var("default_numeric") }}   as   SFDC_parent_and_child_match ,
   {{ var("default_boolean") }}   as   SFDC_parent_churned ,
   {{ var("default_numeric") }}   as   SFDC_parent_et_tam ,
  '{{ var("default_varchar") }}' as SFDC_parent_gsid ,
  '{{ var("default_varchar") }}' as SFDC_parent_id ,
  '{{ var("default_varchar") }}' as SFDC_parent_long_name ,
  '{{ var("default_varchar") }}' as SFDC_parent_mdr ,
  '{{ var("default_varchar") }}' as SFDC_parent_name ,
  '{{ var("default_varchar") }}' as SFDC_parent_name_proper_case ,
  '{{ var("default_varchar") }}' as SFDC_parent_owner_id ,
  '{{ var("default_varchar") }}' as SFDC_parent_uid ,
   {{ var("default_numeric") }}   as   SFDC_pct_afro_amer ,
   {{ var("default_numeric") }}   as   SFDC_pct_asian ,
   {{ var("default_numeric") }}   as   SFDC_pct_hisp ,
   {{ var("default_numeric") }}   as   SFDC_pct_multi_racial ,
   {{ var("default_numeric") }}   as   SFDC_pct_native ,
   {{ var("default_numeric") }}   as   SFDC_pct_white ,
  '{{ var("default_varchar") }}' as SFDC_per_student_expenditures ,
   {{ var("default_numeric") }}   as   SFDC_percent_students_ell ,
  '{{ var("default_varchar") }}' as SFDC_phone ,
  '{{ var("default_varchar") }}' as SFDC_photo_url ,
   {{ var("default_boolean") }}   as   SFDC_platform_sync ,
   {{ var("default_numeric") }}   as   SFDC_poverty_percent_under_age_18 ,
   {{ var("default_numeric") }}   as   SFDC_pre_k_enrollment ,
   {{ var("default_boolean") }}   as   SFDC_priority_account ,
  '{{ var("default_varchar") }}' as SFDC_record_type ,
   {{ var("default_numeric") }}   as   SFDC_reduced_lunch_student ,
   {{ var("default_boolean") }}   as   SFDC_reference_customer ,
  '{{ var("default_varchar") }}' as SFDC_related_activity ,
   {{ var("default_boolean") }}   as   SFDC_related ,
  '{{ var("default_varchar") }}' as SFDC_renewal_forecast_segment ,
  '{{ var("default_varchar") }}' as SFDC_resa_name_proper ,
   {{ var("default_numeric") }}   as   SFDC_resa_uid ,
  '{{ var("default_varchar") }}' as SFDC_sales_owner_field ,
  '{{ var("default_varchar") }}' as SFDC_sales_support_rep ,
   {{ var("default_boolean") }}   as   SFDC_sbqq_co_termed_contracts_combined ,
  '{{ var("default_varchar") }}' as SFDC_sbqq_contract_co_termination ,
   {{ var("default_boolean") }}   as   SFDC_sbqq_preserve_bundle ,
   {{ var("default_numeric") }}   as   SFDC_school_enrollment ,
  '{{ var("default_varchar") }}' as SFDC_school_id ,
  '{{ var("default_varchar") }}' as SFDC_school_type ,
  '{{ var("default_date") }}' as SFDC_school_year_end ,
  '{{ var("default_date") }}' as SFDC_school_year_start ,
   {{ var("default_numeric") }}   as   SFDC_schools_in_district ,
   {{ var("default_boolean") }}   as   SFDC_state_eligible_or_initiative ,
   {{ var("default_boolean") }}   as   SFDC_state_initiative ,
  '{{ var("default_varchar") }}' as SFDC_state_profile ,
   {{ var("default_boolean") }}   as   SFDC_state_program_eligible ,
   {{ var("default_numeric") }}   as   SFDC_student_tam ,
   {{ var("default_boolean") }}   as   SFDC_sync_district ,
   {{ var("default_boolean") }}   as   SFDC_syncing_district ,
  '{{ var("default_date") }}' as SFDC_system_modstamp ,
   {{ var("default_boolean") }}   as   SFDC_target_account ,
   {{ var("default_numeric") }}   as   SFDC_teachers_in_building ,
  '{{ var("default_varchar") }}' as SFDC_technology_equipment ,
   {{ var("default_numeric") }}   as   SFDC_technology_index ,
  '{{ var("default_varchar") }}' as SFDC_technology_measure ,
  '{{ var("default_varchar") }}' as SFDC_technology_supplies_and_purchases ,
  '{{ var("default_varchar") }}' as SFDC_territory ,
  '{{ var("default_varchar") }}' as SFDC_territory_list ,
   {{ var("default_boolean") }}   as   SFDC_test_account ,
  '{{ var("default_varchar") }}' as SFDC_tiered_service_level ,
   {{ var("default_numeric") }}   as   SFDC_time_zone ,
   {{ var("default_numeric") }}   as   SFDC_time_zone_raw ,
  '{{ var("default_varchar") }}' as SFDC_time_zone_transformed ,
  '{{ var("default_varchar") }}' as SFDC_title_iv_funding_21_st_century_grants ,
  '{{ var("default_varchar") }}' as SFDC_title_iv_funding_student_support ,
   {{ var("default_boolean") }}   as   SFDC_top_75_account ,
   {{ var("default_numeric") }}   as   SFDC_total_credits_purchased ,
   {{ var("default_numeric") }}   as   SFDC_total_number_of_schools ,
   {{ var("default_numeric") }}   as   SFDC_total_renewal_arr ,
  '{{ var("default_varchar") }}' as SFDC_trend_district_revenue ,
  '{{ var("default_varchar") }}' as SFDC_trend_enrollment ,
  '{{ var("default_varchar") }}' as SFDC_trend_federal_revenue ,
  '{{ var("default_varchar") }}' as SFDC_trend_instructional_expenditures ,
  '{{ var("default_varchar") }}' as SFDC_trend_local_revenue ,
  '{{ var("default_varchar") }}' as SFDC_trend_state_revenue ,
  '{{ var("default_varchar") }}' as SFDC_trend_title_i_revenue ,
  '{{ var("default_varchar") }}' as SFDC_type ,
  '{{ var("default_varchar") }}' as SFDC_ultimate_account_lifecycle_stage ,
  '{{ var("default_varchar") }}' as SFDC_ultimate_account_owner ,
  '{{ var("default_varchar") }}' as SFDC_ultimate_parent_account ,
  '{{ var("default_varchar") }}' as SFDC_ultimate_parent_billing_state ,
  '{{ var("default_varchar") }}' as SFDC_ultimate_parent_id ,
   {{ var("default_numeric") }}   as   SFDC_ultimate_parent_total_renewal_arr_2 ,
  '{{ var("default_varchar") }}' as SFDC_urban_rural ,
   {{ var("default_boolean") }}   as   SFDC_vidcode_customer_2 ,
  '{{ var("default_varchar") }}' as SFDC_virtual_school ,
  '{{ var("default_varchar") }}' as SFDC_virtual_status_text ,
  '{{ var("default_varchar") }}' as SFDC_website ,
  '{{ var("default_varchar") }}' as SFDC_x_1_1_computing ,
   {{ var("default_numeric") }}   as   SFDC_x_10_th_grade_enrollment ,
   {{ var("default_numeric") }}   as   SFDC_x_11_th_grade_enrollment ,
   {{ var("default_numeric") }}   as   SFDC_x_12_th_grade_enrollment ,
   {{ var("default_numeric") }}   as   SFDC_x_2_nd_grade_enrollment ,
   {{ var("default_boolean") }}   as   SFDC_x_2020_service_purchased ,
   {{ var("default_boolean") }}   as   SFDC_x_21_csa_eol ,
   {{ var("default_boolean") }}   as   SFDC_x_3_plms ,
   {{ var("default_numeric") }}   as   SFDC_x_3_rd_grade_enrollment ,
   {{ var("default_numeric") }}   as   SFDC_x_4_th_grade_enrollment ,
   {{ var("default_numeric") }}   as   SFDC_x_6_th_grade_enrollment ,
   {{ var("default_numeric") }}   as   SFDC_x_7_th_grade_enrollment ,
   {{ var("default_numeric") }}   as   SFDC_x_9_th_grade_enrollment ,
  '{{ var("default_varchar") }}'  as   SFDC_zendesk_domain	,
  '{{ var("default_varchar") }}'  as   SFDC_lcom_organization_id,
  --School (some child accounts info)
{{ var("default_boolean") }} as SFDC_state_initiative_school,
{{ var("default_boolean") }} as SFDC_district_state_initiative_school,
{{ var("default_boolean") }} as SFDC_state_eligible_or_initiative_school,
--District (some parent account info)
{{ var("default_boolean") }} as SFDC_state_initiative_district,
{{ var("default_boolean") }} as SFDC_district_state_initiative_district,
{{ var("default_boolean") }} as SFDC_state_eligible_or_initiative_district,
--Calculated
{{ var("default_boolean") }} as isHighSchool
)
select
    account_id::varchar(300),
    lcom_organization_id :: varchar(300),
    lcom_organization_name :: varchar(270),
    lcom_organization_type :: varchar(20),
    lcom_parent_organization_id :: varchar(270),
    lcom_parent_organization_name :: varchar(270),
    lcom_trial :: boolean,
    lcom_demo :: boolean,
    lcom_postal_code :: varchar(20),
    lcom_state_province_key :: varchar(20),
    lcom_state_province_code :: varchar(20),
    lcom_state_province_name :: varchar(50),
    lcom_country_code :: varchar(20),
    lcom_country_name :: varchar(70),
    lcom_alpha3_code :: varchar(20),
    lcom_numeric_code :: varchar(20),
    lcom_external_sis_id :: varchar(270),
    lcom_nces_id :: varchar(30),
    lcom_created_datetime :: timestamp,
    lcom_modified_datetime :: timestamp,
    lcom_deleted_datetime :: timestamp,
    sfdc_account_id :: varchar(300),
    sfdc_name :: varchar(780),
    sfdc_account_last_activity_date :: date,
    sfdc_account_lifecycle_stage :: varchar(780),
    sfdc_account_management_type :: varchar(20),
    sfdc_act_id :: varchar(30),
    sfdc_actively_prospecting :: boolean,
    sfdc_activity_metric_id :: varchar(30),
    sfdc_activity_metric_rollup_id :: varchar(30),
    sfdc_ae_or_isr :: varchar(20),
    sfdc_agile_id :: varchar(70),
    sfdc_agile_lms :: varchar(4110),
    sfdc_agileed_agile_ed_insert :: boolean,
    sfdc_agileed_agile_ed_key :: varchar(40),
    sfdc_agileed_agile_ed_latest_update_date :: date,
    sfdc_agileed_agile_ed_parent_key :: varchar(40),
    sfdc_agileed_agile_ed_status :: varchar(90),
    sfdc_agileed_agile_ed_up_to_date :: boolean,
    sfdc_agileed_agileed_do_not_update :: boolean,
    sfdc_agileed_connect_link_changed_personnel_titles :: double precision,
    sfdc_agileed_connect_link_district_key :: varchar(40),
    sfdc_agileed_connect_link_file_type :: varchar(250),
    sfdc_agileed_connect_link_hierarchized_personnel :: double precision,
    sfdc_agileed_connect_link_licensed_status :: varchar(70),
    sfdc_agileed_connect_link_personnel_roles :: double precision,
    sfdc_agileed_connect_link_personnel_titles :: double precision,
    sfdc_agileed_last_sync :: timestamp,
    sfdc_agileed_parent_pending :: boolean,
    sfdc_agileed_personnel_last_sync :: timestamp,
    sfdc_alt_phone :: varchar(130),
    sfdc_cares_act_allocation :: double precision,
    sfdc_category :: varchar(780),
    sfdc_check_national_id :: boolean,
    sfdc_closed_district_tx_adoption :: boolean,
    sfdc_code_monkey_customer :: boolean,
    sfdc_codester_id :: varchar(70),
    sfdc_codesters_account_to_be_migrated_to_prod :: boolean,
    sfdc_codesters_customer_2 :: boolean,
    sfdc_codesters_customer_dedupe_flag :: boolean,
    sfdc_company_domain_name :: varchar(780),
    sfdc_completed_onboarding :: boolean,
    sfdc_computer_os :: varchar(780),
    sfdc_contracted_roll_up :: numeric,
    sfdc_county_name :: varchar(780),
    sfdc_created_by_id :: varchar(30),
    sfdc_created_date :: timestamp,
    sfdc_csm_email :: varchar(400),
    sfdc_csm_name :: varchar(380),
    sfdc_current_renewal_arr :: numeric,
    sfdc_current_total_ultimate_parent :: varchar(410),
    sfdc_customer_type :: varchar(20),
    sfdc_data_quality_description :: varchar(70),
    sfdc_data_quality_score :: integer,
    sfdc_de_identified_district :: boolean,
    sfdc_description :: varchar(max),
    sfdc_detailed_grade :: varchar(780),
    sfdc_district :: varchar(780),
    sfdc_district_easy_code_tam :: numeric,
    sfdc_district_easy_tech_tam :: numeric,
    sfdc_district_elementary_teachers :: varchar(110),
    sfdc_district_enrollment :: double precision,
    sfdc_district_expansion_potential :: numeric,
    sfdc_district_faculty_library_media_fte :: double precision,
    sfdc_district_instructional_expenditures :: varchar(310),
    sfdc_district_k_8_enrollment :: double precision,
    sfdc_district_kindergarten_teachers :: varchar(110),
    sfdc_district_local_revenue_cities :: double precision,
    sfdc_district_local_revenue_other_leas :: varchar(70),
    sfdc_district_local_revenue_other_taxes :: varchar(70),
    sfdc_district_local_revenue_property_taxes :: varchar(70),
    sfdc_district_nces :: varchar(780),
    sfdc_district_presence :: double precision,
    sfdc_district_state_initiative :: boolean,
    sfdc_district_total_capital_outlay :: varchar(780),
    sfdc_district_total_expenditures :: varchar(780),
    sfdc_district_total_expense_per_student :: varchar(110),
    sfdc_district_total_fed_revenue :: varchar(780),
    sfdc_district_total_local_revenue :: varchar(780),
    sfdc_district_total_revenue :: varchar(780),
    sfdc_district_total_state_revenue :: varchar(780),
    sfdc_district_total_tam :: numeric,
    sfdc_district_type :: varchar(780),
    sfdc_dq_opportunities :: bigint,
    sfdc_easy_tech_customer :: boolean,
    sfdc_easy_tech_tam :: numeric,
    sfdc_easy_tech_tam_captured :: double precision,
    sfdc_ec_tam :: double precision,
    sfdc_education_climate_index :: double precision,
    sfdc_education_type :: varchar(4110),
    sfdc_eighth_grade_enrollment :: double precision,
    sfdc_email_domain :: varchar(780),
    sfdc_enrollment_advanced_placement :: varchar(780),
    sfdc_enrollment_band :: varchar(30),
    sfdc_enrollment_tier :: varchar(20),
    sfdc_esser_funding :: varchar(210),
    sfdc_et_tam :: double precision,
    sfdc_exes_campaign :: boolean,
    sfdc_fifth_grade_enrollment :: double precision,
    sfdc_first_grade_enrollment :: double precision,
    sfdc_first_name :: varchar(1550),
    sfdc_fiscal_career_and_tech_federal :: varchar(780),
    sfdc_fiscal_career_and_tech_state :: varchar(780),
    sfdc_fiscal_career_and_tech_teacher_salar :: varchar(780),
    sfdc_fiscal_title_i_eligible_school :: varchar(780),
    sfdc_fiscal_title_i_funding :: numeric,
    sfdc_fiscal_title_i_percentage :: double precision,
    sfdc_fiscal_title_i_school :: varchar(780),
    sfdc_fiscal_title_i_school_yes_no :: varchar(780),
    sfdc_fiscal_title_i_schoolwide :: varchar(780),
    sfdc_fiscal_title_i_schoolwide_yes_no :: varchar(780),
    sfdc_free_lunch_students :: varchar(780),
    sfdc_free_reduced_lunch :: double precision,
    sfdc_gainsight_customer :: boolean,
    sfdc_gainsight_house :: boolean,
    sfdc_google_integration :: boolean,
    sfdc_governor :: varchar(780),
    sfdc_governor_s_party_affiliation :: varchar(780),
    sfdc_grade_level_detail :: varchar(880),
    sfdc_grade_levels :: varchar(4110),
    sfdc_has_codesters_child_accounts :: boolean,
    sfdc_hi_speed_classroom_internet :: varchar(780),
    sfdc_hi_speed_internet :: varchar(780),
    sfdc_hml_title_i_funding :: varchar(780),
    sfdc_hml_title_i_per_student :: varchar(780),
    sfdc_house_account :: boolean,
    sfdc_i_pad_schools_percent :: double precision,
    sfdc_i_pads_for_instruction :: varchar(780),
    sfdc_ima_coordinator_identified :: boolean,
    sfdc_inst_uid :: varchar(780),
    sfdc_k_12_enrollment :: double precision,
    sfdc_k_5_enrollment :: double precision,
    sfdc_k_8_district_presence :: double precision,
    sfdc_k_8_enrollment :: double precision,
    sfdc_key_account :: boolean,
    sfdc_kindergarten_enrollment :: double precision,
    sfdc_known_duplicate :: boolean,
    sfdc_last_activity_date :: date,
    sfdc_last_activity_logged_on :: date,
    sfdc_last_modified_by_id :: varchar(30),
    sfdc_last_modified_date :: timestamp,
    sfdc_last_name :: varchar(780),
    sfdc_lcom_account :: varchar(30),
    sfdc_lcom_account_class :: varchar(780),
    sfdc_lcom_account_count :: bigint,
    sfdc_lcom_organization :: varchar(30),
    sfdc_lcom_organization_count :: bigint,
    sfdc_lcom_organization_has_parent :: boolean,
    sfdc_learn_dash_code_sent :: boolean,
    sfdc_les_opp :: boolean,
    sfdc_license_consumption :: double precision,
    sfdc_map_tracker :: boolean,
    sfdc_mdr_number :: varchar(60),
    sfdc_mi_pilot :: boolean,
    sfdc_multi_tiered_account :: boolean,
    sfdc_name_with_lcom_organization_info :: varchar(1280),
    sfdc_national_district_id :: varchar(780),
    sfdc_national_school_id :: varchar(1540),
    sfdc_nc_tier_1 :: boolean,
    sfdc_nces_lea_id :: varchar(780),
    sfdc_nces_unique_id :: varchar(780),
    sfdc_net_suite_id :: varchar(780),
    sfdc_net_suite_link :: varchar(880),
    sfdc_netsuite_account_number :: varchar(100),
    sfdc_no_of_child_account :: double precision,
    sfdc_nps_count :: bigint,
    sfdc_nps_score :: double precision,
    sfdc_nps_sum :: numeric,
    sfdc_num_opps :: bigint,
    sfdc_number_of_2020_opps :: bigint,
    sfdc_number_of_active_easy_tech_subscriptions :: double precision,
    sfdc_number_of_active_vidcode_subscriptions :: double precision,
    sfdc_number_of_elementary_schools :: double precision,
    sfdc_number_of_high_schools :: double precision,
    sfdc_number_of_k_8_buildings :: double precision,
    sfdc_number_of_middle_schools :: double precision,
    sfdc_number_of_open_opportunities :: bigint,
    sfdc_number_of_open_opps :: bigint,
    sfdc_number_of_page_views :: double precision,
    sfdc_number_of_renewal_opps :: bigint,
    sfdc_number_of_schools :: double precision,
    sfdc_number_of_sessions :: double precision,
    sfdc_number_of_title_i_schools :: double precision,
    sfdc_number_of_won_renewal_opportunities :: bigint,
    sfdc_open_opportunity_amount :: numeric,
    sfdc_open_renewal_opportunities :: bigint,
    sfdc_org_type :: varchar(780),
    sfdc_otc_provisioned :: boolean,
    sfdc_owner :: varchar(430),
    sfdc_owner_id :: varchar(30),
    sfdc_owner_name_text :: varchar(380),
    sfdc_parent_account_owner :: varchar(380),
    sfdc_parent_and_child_match :: integer,
    sfdc_parent_churned :: boolean,
    sfdc_parent_et_tam :: numeric,
    sfdc_parent_gsid :: varchar(160),
    sfdc_parent_id :: varchar(30),
    sfdc_parent_long_name :: varchar(370),
    sfdc_parent_mdr :: varchar(60),
    sfdc_parent_name :: varchar(780),
    sfdc_parent_name_proper_case :: varchar(370),
    sfdc_parent_owner_id :: varchar(30),
    sfdc_parent_uid :: varchar(20),
    sfdc_pct_afro_amer :: double precision,
    sfdc_pct_asian :: double precision,
    sfdc_pct_hisp :: double precision,
    sfdc_pct_multi_racial :: double precision,
    sfdc_pct_native :: double precision,
    sfdc_pct_white :: double precision,
    sfdc_per_student_expenditures :: varchar(310),
    sfdc_percent_students_ell :: double precision,
    sfdc_phone :: varchar(130),
    sfdc_photo_url :: varchar(780),
    sfdc_platform_sync :: boolean,
    sfdc_poverty_percent_under_age_18 :: double precision,
    sfdc_pre_k_enrollment :: double precision,
    sfdc_priority_account :: boolean,
    sfdc_record_type :: varchar(780),
    sfdc_reduced_lunch_student :: double precision,
    sfdc_reference_customer :: boolean,
    sfdc_related_activity :: varchar(880),
    sfdc_related :: boolean,
    sfdc_renewal_forecast_segment :: varchar(30),
    sfdc_resa_name_proper :: varchar(370),
    sfdc_resa_uid :: double precision,
    sfdc_sales_owner_field :: varchar(30),
    sfdc_sales_support_rep :: varchar(30),
    sfdc_sbqq_co_termed_contracts_combined :: boolean,
    sfdc_sbqq_contract_co_termination :: varchar(780),
    sfdc_sbqq_preserve_bundle :: boolean,
    sfdc_school_enrollment :: double precision,
    sfdc_school_id :: varchar(780),
    sfdc_school_type :: varchar(780),
    sfdc_school_year_end :: date,
    sfdc_school_year_start :: date,
    sfdc_schools_in_district :: double precision,
    sfdc_state_eligible_or_initiative :: boolean,
    sfdc_state_initiative :: boolean,
    sfdc_state_profile :: varchar(30),
    sfdc_state_program_eligible :: boolean,
    sfdc_student_tam :: double precision,
    sfdc_sync_district :: boolean,
    sfdc_syncing_district :: boolean,
    sfdc_system_modstamp :: timestamp,
    sfdc_target_account :: boolean,
    sfdc_teachers_in_building :: double precision,
    sfdc_technology_equipment :: varchar(780),
    sfdc_technology_index :: double precision,
    sfdc_technology_measure :: varchar(70),
    sfdc_technology_supplies_and_purchases :: varchar(780),
    sfdc_territory :: varchar(780),
    sfdc_territory_list :: varchar(780),
    sfdc_test_account :: boolean,
    sfdc_tiered_service_level :: varchar(780),
    sfdc_time_zone :: double precision,
    sfdc_time_zone_raw :: double precision,
    sfdc_time_zone_transformed :: varchar(30),
    sfdc_title_iv_funding_21_st_century_grants :: varchar(210),
    sfdc_title_iv_funding_student_support :: varchar(210),
    sfdc_top_75_account :: boolean,
    sfdc_total_credits_purchased :: double precision,
    sfdc_total_number_of_schools :: double precision,
    sfdc_total_renewal_arr :: numeric,
    sfdc_trend_district_revenue :: varchar(780),
    sfdc_trend_enrollment :: varchar(780),
    sfdc_trend_federal_revenue :: varchar(780),
    sfdc_trend_instructional_expenditures :: varchar(780),
    sfdc_trend_local_revenue :: varchar(780),
    sfdc_trend_state_revenue :: varchar(780),
    sfdc_trend_title_i_revenue :: varchar(780),
    sfdc_type :: varchar(780),
    sfdc_ultimate_account_lifecycle_stage :: varchar(780),
    sfdc_ultimate_account_owner :: varchar(380),
    sfdc_ultimate_parent_account :: varchar(780),
    sfdc_ultimate_parent_billing_state :: varchar(250),
    sfdc_ultimate_parent_id :: varchar(30),
    sfdc_ultimate_parent_total_renewal_arr_2 :: numeric,
    sfdc_urban_rural :: varchar(40),
    sfdc_vidcode_customer_2 :: boolean,
    sfdc_virtual_school :: varchar(780),
    sfdc_virtual_status_text :: varchar(780),
    sfdc_website :: varchar(780),
    sfdc_x_1_1_computing :: varchar(780),
    sfdc_x_10_th_grade_enrollment :: double precision,
    sfdc_x_11_th_grade_enrollment :: double precision,
    sfdc_x_12_th_grade_enrollment :: double precision,
    sfdc_x_2_nd_grade_enrollment :: double precision,
    sfdc_x_2020_service_purchased :: boolean,
    sfdc_x_21_csa_eol :: boolean,
    sfdc_x_3_plms :: boolean,
    sfdc_x_3_rd_grade_enrollment :: double precision,
    sfdc_x_4_th_grade_enrollment :: double precision,
    sfdc_x_6_th_grade_enrollment :: double precision,
    sfdc_x_7_th_grade_enrollment :: double precision,
    sfdc_x_9_th_grade_enrollment :: double precision,
    sfdc_zendesk_domain :: varchar(1550),
    SFDC_lcom_organization_id :: varchar(300),
    sfdc_state_initiative_school :: boolean,
    sfdc_district_state_initiative_school :: boolean,
    sfdc_state_eligible_or_initiative_school :: boolean,
    sfdc_state_initiative_district :: boolean,
    sfdc_district_state_initiative_district :: boolean,
    sfdc_state_eligible_or_initiative_district :: boolean,
    --Calculated
isHighSchool:: boolean,
    '{{ var("loaddate") }}'::timestamp as loaddate
FROM data