{{ config(materialized='ephemeral') }}

with data as (
select
account_id,
lcom_organization_id,
case when lcom_trial then 1 else 0 end lcom_trial,
case when lcom_demo then 1 else 0 end lcom_demo,
lcom_country_name,
lcom_organization_name,
lcom_organization_type,
lcom_parent_organization_name,
lcom_state_province_code,
sfdc_account_id,
sfdc_parent_id,
SFDC_record_type,
sfdc_current_renewal_arr,
case when sfdc_state_initiative then 1 else 0 end sfdc_state_initiative,
case when sfdc_state_initiative_school then 1 else 0 end sfdc_state_initiative_school,
sfdc_owner_id,
sfdc_owner_name_text,
sfdc_billing_state,
sfdc_billing_state_code,
sfdc_grade_levels,
sfdc_k_12_enrollment,
sfdc_k_8_enrollment,
sfdc_name,
sfdc_parent_name,
sfdc_ultimate_account_owner,
sfdc_ultimate_parent_account,
sfdc_ultimate_parent_billing_state,
sfdc_ultimate_parent_id,
sfdc_urban_rural,
case when isHighSchool then 1 else 0 end isHighSchool,
sfdc_billing_country,
sfdc_billing_country_code,
sfdc_district_enrollment,
sfdc_school_enrollment,
case when sfdc_state_program_eligible then 1 else 0 end sfdc_state_program_eligible,
sfdc_county_name,
sfdc_customer_level,
sfdc_customer_level_override,
lcom_parent_organization_id,
GREATEST(lcom_modified_datetime, sfdc_last_modified_date, lcom_created_datetime,sfdc_created_date,'1900-01-01'::date):: timestamp  last_modified_date
from {{ ref("dim_account") }}
)
select
account_id,
lcom_organization_id,
lcom_trial,
lcom_demo,
lcom_country_name,
lcom_organization_name,
lcom_organization_type,
lcom_parent_organization_name,
lcom_state_province_code,
sfdc_account_id,
sfdc_parent_id,
SFDC_record_type,
sfdc_current_renewal_arr,
sfdc_state_initiative,
sfdc_state_initiative_school,
sfdc_owner_id,
sfdc_owner_name_text,
sfdc_billing_state,
sfdc_billing_state_code,
sfdc_grade_levels,
sfdc_k_12_enrollment,
sfdc_k_8_enrollment,
sfdc_name,
sfdc_parent_name,
sfdc_ultimate_account_owner,
sfdc_ultimate_parent_account,
sfdc_ultimate_parent_billing_state,
sfdc_ultimate_parent_id,
sfdc_urban_rural,
isHighSchool,
sfdc_billing_country,
sfdc_billing_country_code,
sfdc_district_enrollment,
sfdc_school_enrollment,
sfdc_state_program_eligible,
sfdc_county_name,
sfdc_customer_level,
sfdc_customer_level_override,
lcom_parent_organization_id,
last_modified_date
from data