{{
    config(

        materialized='table',        
        sort='start_date', 
        dist='account_id'  
        
        )
}}
with 
staging as (
select
    {{ safe_select_list_from_profiles(
        table_name='opportunity',
        alias='sfdc_opportunity',
        used_columns=[ 
            'id','name','account_id',
'amount','amount_won_c','arr_bands_c',
'arr_c','arr_new_business_c','arr_renewal_c','arr_upsell_c','arr_won_c',
'billing_addressee_c','billing_city_c','billing_state_c','billing_street_c',
'billing_zipcode_c','churn_date_c','churn_formula_c','close_date',
'combined_arr_c','contract_id','created_by_id',
'created_date','data_quality_description_c',
'data_quality_score_c','description',
'disable_auto_renewal_opp_c','downsell_c','end_date_c',
'invoiced_date_c',
'last_modified_by_id','last_modified_date',
'license_unenforced_c','loss_reason_c','loss_notes_c',
'multi_year_arr_c','multi_year_order_c',
'netsuite_id_c','new_biz_arr_trigger_c',
'nnarr_c','nrr_renewal_c',
'number_of_schools_c','number_of_students_c','number_c','opportunity_score_id',
'owner_id','paid_date_c','payment_terms_c',
'po_amount_c',
'po_number_c','price_increase_arr_c','pricebook_2_id',
'probability',
'record_type_id',
'renewable_revenue_c',
'renewal_opportunity_c',
'sbqq_primary_quote_c','school_list_c',
'source_opp_arr_c','stage_name',
'start_date_c',
'total_arr_bookings_c',
'true_arr_c','true_arr_formula_c','true_renewal_arr_c',
'x_1_st_contact_c','x_1_st_contact_email_c',
'x_1_st_contact_name_c','x_1_st_contact_role_c',
'x_2_nd_contact_email_c','x_2_nd_contact_name_c','x_3_rd_contact_email_c',
'x_3_rd_contact_name_c','test_account_c','campaign_id',
'contact_id',
'x_2_nd_contact_c',
'x_3_rd_contact_c','license_provisioned_date_c','subscription_start_date_c','subscription_end_date_c',
'quota_c','quote_contract_type_c','quote_created_date_c','quote_expiry_date_c',
'quote_list_amount_c','quote_name_c','quote_notes_c','quote_start_date_c',
'quote_total_discount_c','remaining_quota_c'
            ],
        profile_src=('profiles','vw_sfdc_schema_audit'),
        base_profile='base',
        current_profile='current'
    ) }}
from {{ source('fivetran_salesforce_quickstart', 'opportunity') }} sfdc_opportunity
)
,data as (
select 
   isnull(o.id,   '{{ var("default_ID") }}') as opportunity_id,
    isnull(o.name, '{{ var("default_varchar") }}') as name,
    isnull(a.account_id, '{{ var("default_ID") }}') as account_id,
    isnull(o.account_id, '{{ var("default_ID") }}') as sfdc_account_id,
    isnull(o.amount, {{ var("default_numeric") }}) as amount,
    isnull(o.amount_won_c, {{ var("default_numeric") }}) as amount_won,
    isnull(o.arr_bands_c, '{{ var("default_varchar") }}') as arr_bands,
    isnull(o.arr_c, {{ var("default_numeric") }}) as arr,
    isnull(o.arr_new_business_c, {{ var("default_numeric") }}) as arr_new_business,
    isnull(o.arr_renewal_c, {{ var("default_numeric") }}) as arr_renewal,
    isnull(o.arr_upsell_c, {{ var("default_numeric") }}) as arr_upsell,
    isnull(o.arr_won_c, {{ var("default_numeric") }}) as arr_won,
    isnull(o.billing_addressee_c, '{{ var("default_varchar") }}') as billing_addressee,
    isnull(o.billing_city_c, '{{ var("default_varchar") }}') as billing_city,
    isnull(o.billing_state_c, '{{ var("default_varchar") }}') as billing_state,
    isnull(o.billing_street_c, '{{ var("default_varchar") }}') as billing_street,
    isnull(o.billing_zipcode_c, '{{ var("default_varchar") }}') as billing_zipcode,
    isnull(o.campaign_id, '{{ var("default_ID") }}') as campaign_id,       
    isnull(o.contact_id, '{{ var("default_ID") }}') as contact_id,
    isnull(o.churn_date_c, '{{ var("default_date") }}') as churn_date,
    isnull(o.churn_formula_c, {{ var("default_numeric") }}) as churn_formula,
    isnull(o.close_date, '{{ var("default_date") }}') as close_date,
    isnull(o.combined_arr_c, {{ var("default_numeric") }}) as combined_arr,
    isnull(o.contract_id, '{{ var("default_varchar") }}') as contract_id,
    isnull(o.created_by_id, '{{ var("default_varchar") }}') as created_by_id,
    isnull(o.created_date AT TIME ZONE 'PST', '{{ var("default_date") }}') as created_date,
    isnull(o.data_quality_description_c, '{{ var("default_varchar") }}') as data_quality_description,
    isnull(o.data_quality_score_c, {{ var("default_numeric") }}) as data_quality_score,
    isnull(o.description, '{{ var("default_varchar") }}') as description,
    isnull(o.disable_auto_renewal_opp_c, {{ var("default_boolean") }}) as disable_auto_renewal_opp,
    isnull(o.downsell_c, {{ var("default_numeric") }}) as downsell,
    isnull(o.end_date_c, '{{ var("default_date") }}') as end_date,
    isnull(o.invoiced_date_c, '{{ var("default_date") }}') as invoiced_date,
    isnull(o.last_modified_by_id, '{{ var("default_varchar") }}') as last_modified_by_id,
    isnull(o.last_modified_date AT TIME ZONE 'PST', '{{ var("default_date") }}') as last_modified_date,
    isnull(o.license_unenforced_c, {{ var("default_boolean") }}) as license_unenforced,
    isnull(o.license_provisioned_date_c,   '{{ var("default_date") }}') as license_provisioned_date ,
    isnull(o.loss_reason_c, '{{ var("default_varchar") }}') as loss_reason,
    isnull(o.loss_notes_c, '{{ var("default_varchar") }}') as loss_notes,
    isnull(o.multi_year_arr_c, {{ var("default_numeric") }}) as multi_year_arr,
    isnull(o.multi_year_order_c, {{ var("default_boolean") }}) as multi_year_order,
    isnull(o.netsuite_id_c, '{{ var("default_varchar") }}') as netsuite_id,
    isnull(o.new_biz_arr_trigger_c, {{ var("default_numeric") }}) as new_biz_arr_trigger,
    isnull(o.nnarr_c, {{ var("default_numeric") }}) as nnarr,
    isnull(o.nrr_renewal_c, {{ var("default_numeric") }}) as nrr_renewal,
    isnull(o.number_of_schools_c, {{ var("default_numeric") }}) as number_of_schools,
    isnull(o.number_of_students_c, {{ var("default_numeric") }}) as number_of_students,
    isnull(rt.name, '{{ var("default_varchar") }}') as opp_record_type,
    isnull(o.number_c, '{{ var("default_varchar") }}') as opportunity_number,
    isnull(o.opportunity_score_id, '{{ var("default_varchar") }}') as opportunity_score_id,
    isnull(o.owner_id, '{{ var("default_ID") }}') as owner_id,
    isnull(o.paid_date_c, '{{ var("default_date") }}') as paid_date,
    isnull(o.payment_terms_c, '{{ var("default_varchar") }}') as payment_terms,
    isnull(o.po_amount_c, {{ var("default_numeric") }}) as po_amount,
    isnull(o.po_number_c, '{{ var("default_varchar") }}') as po_number,
    isnull(o.price_increase_arr_c, {{ var("default_numeric") }}) as price_increase_arr,
    isnull(o.pricebook_2_id, '{{ var("default_varchar") }}') as pricebook_2_id,
    isnull(o.probability, {{ var("default_numeric") }}) as probability,
    isnull(o.quota_c,   '{{ var("default_varchar") }}') as quota ,
    isnull(o.quote_contract_type_c,   '{{ var("default_varchar") }}') as quote_contract_type ,
    isnull(o.quote_created_date_c,   '{{ var("default_date") }}') as quote_created_date ,
    isnull(o.quote_expiry_date_c,   '{{ var("default_date") }}') as quote_expiry_date ,
    isnull(o.quote_list_amount_c , {{ var("default_numeric") }}) as quote_list_amount ,
    isnull(o.quote_name_c,   '{{ var("default_varchar") }}') as quote_name ,
    isnull(o.quote_notes_c,   '{{ var("default_varchar") }}') as quote_notes ,
    isnull(o.quote_start_date_c,   '{{ var("default_date") }}') as quote_start_date ,
    isnull(o.quote_total_discount_c , {{ var("default_numeric") }}) as quote_total_discount ,
    isnull(o.remaining_quota_c , {{ var("default_numeric") }}) as remaining_quota ,
    isnull(o.renewable_revenue_c, {{ var("default_numeric") }}) as renewable_revenue,
    isnull(o.renewal_opportunity_c, '{{ var("default_varchar") }}') as renewal_opportunity_id,
    isnull(o.sbqq_primary_quote_c, '{{ var("default_varchar") }}') as sbqq_primary_quote,
    isnull(o.school_list_c, '{{ var("default_varchar") }}') as school_list,
    isnull(o.source_opp_arr_c, {{ var("default_numeric") }}) as source_opp_arr,
    isnull(o.stage_name, '{{ var("default_varchar") }}') as stage_name,
    isnull(o.start_date_c, '{{ var("default_date") }}') as start_date,
    isnull(o.subscription_end_date_c,   '{{ var("default_date") }}') as subscription_end_date ,
    isnull(o.subscription_start_date_c,   '{{ var("default_date") }}') as subscription_start_date ,
    isnull(o.total_arr_bookings_c, {{ var("default_numeric") }}) as total_arr_bookings,
    isnull(o.true_arr_c, {{ var("default_numeric") }}) as true_arr,
    isnull(o.true_arr_formula_c, {{ var("default_numeric") }}) as true_arr_formula,
    isnull(o.true_renewal_arr_c, {{ var("default_numeric") }}) as true_renewal_arr,
    isnull(o.x_1_st_contact_c, '{{ var("default_ID") }}') as x_1_st_contact,
    isnull(o.x_1_st_contact_email_c, '{{ var("default_varchar") }}') as x_1_st_contact_email,
    isnull(o.x_1_st_contact_name_c, '{{ var("default_varchar") }}') as x_1_st_contact_name,
    isnull(o.x_1_st_contact_role_c, '{{ var("default_varchar") }}') as x_1_st_contact_role,
    isnull(o.x_2_nd_contact_c, '{{ var("default_ID") }}') as x_2_nd_contact,
    isnull(o.x_2_nd_contact_email_c, '{{ var("default_varchar") }}') as x_2_nd_contact_email,
    isnull(o.x_2_nd_contact_name_c, '{{ var("default_varchar") }}') as x_2_nd_contact_name,
    isnull(o.x_3_rd_contact_c, '{{ var("default_ID") }}') as x_3_rd_contact,   
    isnull(o.x_3_rd_contact_email_c, '{{ var("default_varchar") }}') as x_3_rd_contact_email,
    isnull(o.x_3_rd_contact_name_c, '{{ var("default_varchar") }}') as x_3_rd_contact_name
from
staging as o
left outer join  {{ ref('dim_account') }} as a
on o.account_id = a.SFDC_account_id
left outer join {{ source('fivetran_salesforce_quickstart', 'record_type') }} rt
on o.record_type_id = rt.id
where o.test_account_c = false
)
select
    opportunity_id::varchar(300),
    name::varchar(300),
    account_id::varchar(300),
    sfdc_account_id::varchar(300),
    amount::numeric(35,10),
    amount_won::numeric(35,10),
    arr_bands::varchar(30),
    arr::double precision,
    arr_new_business::numeric(38,10),
    arr_renewal::numeric(38,10),
    arr_upsell::numeric(38,10),
    arr_won::numeric(38,10),
    billing_addressee::varchar(160),
    billing_city::varchar(120),
    billing_state::varchar(780),
    billing_street::varchar(780),
    billing_zipcode::varchar(120),
    campaign_id::varchar(300),
    contact_id::varchar(300),
    churn_date::date,
    churn_formula::double precision,
    close_date::date,
    combined_arr::numeric(38,10),
    contract_id::varchar(30),
    created_by_id::varchar(30),
    created_date::timestamp,
    data_quality_description::varchar(70),
    data_quality_score::integer,
    description::varchar(max),
    disable_auto_renewal_opp::boolean,
    downsell::double precision,
    end_date::date,
    invoiced_date::date,
    last_modified_by_id::varchar(30),
    last_modified_date::timestamp,
    license_provisioned_date ::date	,
    license_unenforced::boolean,
    loss_reason::varchar(765),
    loss_notes::varchar(3000),
    multi_year_arr::numeric(38,10),
    multi_year_order::boolean,
    netsuite_id::varchar(780),
    new_biz_arr_trigger::numeric(38,10),
    nnarr::double precision,
    nrr_renewal::numeric(38,10),
    number_of_schools::double precision,
    number_of_students::double precision,
    opp_record_type::varchar(20),
    opportunity_number::varchar(100),
    opportunity_score_id::varchar(30),
    owner_id::varchar(30),
    paid_date::date,
    payment_terms::varchar(780),
    po_amount::numeric(35,10),
    po_number::varchar(90),
    price_increase_arr::double precision,
    pricebook_2_id::varchar(30),
    probability::double precision,
    quota::varchar(250)	,
    quote_contract_type::varchar(780)	,
    quote_created_date::date	,
    quote_expiry_date::date	,
    quote_list_amount::double precision	,
    quote_name::varchar(250)	,
    quote_notes::varchar(780)	,
    quote_start_date::date	,
    quote_total_discount::double precision	,
    remaining_quota::double precision	,
    renewable_revenue::numeric(38,10),
    renewal_opportunity_id::varchar(300),
    sbqq_primary_quote::varchar(30),
    school_list::varchar(max),
    source_opp_arr::numeric(38,10),
    stage_name::varchar(780),
    start_date::date,
    subscription_end_date::date	,
    subscription_start_date::date	,
    total_arr_bookings::numeric(38,10),
    true_arr::numeric(35,10),
    true_arr_formula::double precision,
    true_renewal_arr::double precision,
    x_1_st_contact::varchar(300),
    x_1_st_contact_email::varchar(250),
    x_1_st_contact_name::varchar(780),
    x_1_st_contact_role::varchar(780),
    x_2_nd_contact::varchar(300),
    x_2_nd_contact_email::varchar(250),
    x_2_nd_contact_name::varchar(780),
    x_3_rd_contact::varchar(300),
    x_3_rd_contact_email::varchar(250),
    x_3_rd_contact_name::varchar(780),
    '{{ var("loaddate") }}'::timestamp as loaddate
from data
