{{
    config(

        materialized='table',        
        sort='start_date', 
        dist='account_id',
        post_hook=['{{ update_history_table_changed_uk("revenue", "fact_opportunity_history") }}' ],
        sql_header = 'SET enable_numeric_rounding TO ON;'    
        )
}}
with 
staging as (
select
    {{ safe_select_list_from_profiles(
        table_name='opportunity',
        alias='sfdc_opportunity',
        used_columns=[ 
            'id','name','account_id',
'amount','amount_won_c','arr_bands_c',
'arr_c','arr_new_business_c','arr_renewal_c','arr_upsell_c','arr_won_c',
'billing_addressee_c','billing_city_c','billing_state_c','billing_street_c',
'billing_zipcode_c','churn_date_c','churn_formula_c','close_date',
'combined_arr_c','contract_id','created_by_id',
'created_date',
'description',
'disable_auto_renewal_opp_c','downsell_c','end_date_c',
'invoiced_date_c',
'last_modified_by_id','last_modified_date',
'license_unenforced_c','closed_reason_c','closed_notes_c',
'multi_year_arr_c','multi_year_order_c',
'netsuite_id_c','new_biz_arr_trigger_c',
'nnarr_c','nrr_renewal_c',
'number_of_schools_c','number_of_students_c','number_c','opportunity_score_id',
'owner_id','paid_date_c','payment_terms_c',
'po_amount_c',
'po_number_c','price_increase_arr_c','pricebook_2_id',
'probability',
'record_type_id',
'renewable_revenue_c',
'renewal_opportunity_c',
'sbqq_primary_quote_c','school_list_c',
'source_opp_arr_c','stage_name',
'start_date_c', 'subscription_term_c',
'total_arr_bookings_c',
'true_arr_c','true_arr_formula_c','true_renewal_arr_c',
'x_1_st_contact_c','x_1_st_contact_email_c',
'x_1_st_contact_name_c','x_1_st_contact_role_c',
'x_2_nd_contact_email_c','x_2_nd_contact_name_c','x_3_rd_contact_email_c',
'x_3_rd_contact_name_c','test_account_c','campaign_id',
'contact_id',
'x_2_nd_contact_c',
'x_3_rd_contact_c','license_provisioned_date_c','subscription_start_date_c','subscription_end_date_c',
'quota_c','quote_contract_type_c','quote_created_date_c','quote_expiry_date_c',
'quote_list_amount_c','quote_name_c','quote_notes_c','quote_start_date_c','progressive_billing_c','Override_ARR_c'
            ],
        profile_src=('profiles','vw_sfdc_schema_audit'),
        base_profile='base',
        current_profile='current'
    ) }}
from {{ source('fivetran_salesforce_quickstart', 'opportunity') }} sfdc_opportunity
)
,staging_quote as (
    select
    {{ safe_select_list_from_profiles(
        table_name='sbqq_quote_c',
        alias='sfdc_quote',
        used_columns=[ 
            'id',
            'progressive_payment_amount_2_c',
            'progressive_payment_amount_3_c',
            'progressive_payment_amount_4_c',
            'progressive_payment_amount_5_c',
            'progressive_payment_date_2_c',
            'progressive_payment_date_3_c',
            'progressive_payment_date_4_c',
            'progressive_payment_date_5_c',
            'Standard_Discount_c',
            'Contract_Type_c'
            ],
        profile_src=('profiles','vw_sfdc_schema_audit'),
        base_profile='base',
        current_profile='current'
    ) }}
from {{ source('fivetran_salesforce_quickstart', 'sbqq_quote_c') }} sfdc_quote
)
,data as (
select 
   isnull(o.id,   '{{ var("default_ID") }}') as opportunity_id,
    isnull(o.name, '{{ var("default_varchar") }}') as name,
    isnull(a.account_id, '{{ var("default_ID") }}') as account_id,
    isnull(o.account_id, '{{ var("default_ID") }}') as sfdc_account_id,
    isnull(o.amount, {{ var("default_numeric") }}) as amount,
    isnull(o.amount_won_c, {{ var("default_numeric") }}) as amount_won,
    isnull(o.arr_bands_c, '{{ var("default_varchar") }}') as arr_bands,
    isnull(o.arr_c, {{ var("default_numeric") }}) as arr,
    isnull(o.arr_new_business_c, {{ var("default_numeric") }}) as arr_new_business,
    isnull(o.arr_renewal_c, {{ var("default_numeric") }}) as arr_renewal,
    isnull(o.arr_upsell_c, {{ var("default_numeric") }}) as arr_upsell,
    isnull(o.arr_won_c, {{ var("default_numeric") }}) as arr_won,
    isnull(o.billing_addressee_c, '{{ var("default_varchar") }}') as billing_addressee,
    isnull(o.billing_city_c, '{{ var("default_varchar") }}') as billing_city,
    isnull(o.billing_state_c, '{{ var("default_varchar") }}') as billing_state,
    isnull(o.billing_street_c, '{{ var("default_varchar") }}') as billing_street,
    isnull(o.billing_zipcode_c, '{{ var("default_varchar") }}') as billing_zipcode,
    isnull(o.campaign_id, '{{ var("default_ID") }}') as campaign_id,       
    isnull(o.contact_id, '{{ var("default_ID") }}') as contact_id,
    isnull(o.churn_date_c, '{{ var("default_date") }}') as churn_date,
    isnull(o.churn_formula_c, {{ var("default_numeric") }}) as churn_formula,
    isnull(o.close_date, '{{ var("default_date") }}') as close_date,
    isnull(o.combined_arr_c, {{ var("default_numeric") }}) as combined_arr,
    isnull(o.contract_id, '{{ var("default_varchar") }}') as contract_id,
    isnull(o.created_by_id, '{{ var("default_varchar") }}') as created_by_id,
    isnull(o.created_date AT TIME ZONE 'PST', '{{ var("default_date") }}') as created_date,
    isnull(o.description, '{{ var("default_varchar") }}') as description,
    isnull(o.disable_auto_renewal_opp_c, {{ var("default_boolean") }}) as disable_auto_renewal_opp,
    isnull(q.Standard_Discount_c::numeric(16,2)/100, {{ var("default_numeric") }}) as multi_year_discount_rate,
    isnull(q.Contract_Type_c, '{{ var("default_varchar") }}') as contract_type,
    isnull(o.downsell_c, {{ var("default_numeric") }}) as downsell,
    isnull(o.end_date_c, '{{ var("default_date") }}') as end_date,
    isnull(o.invoiced_date_c, '{{ var("default_date") }}') as invoiced_date,
    isnull(hd.deal_type, '{{ var("default_varchar") }}') as ecommerce_cart,
    isnull(o.last_modified_by_id, '{{ var("default_varchar") }}') as last_modified_by_id,
    isnull(o.last_modified_date AT TIME ZONE 'PST', '{{ var("default_date") }}') as last_modified_date,
    isnull(o.license_unenforced_c, {{ var("default_boolean") }}) as license_unenforced,
    isnull(o.license_provisioned_date_c,   '{{ var("default_date") }}') as license_provisioned_date ,
    case when o.stage_name='Closed Lost' then  isnull(o.closed_reason_c, '{{ var("default_varchar") }}') else '{{ var("default_varchar") }}' end as loss_reason,
    case when o.stage_name='Closed Lost' then  isnull(o.closed_notes_c, '{{ var("default_varchar") }}') else '{{ var("default_varchar") }}' end as loss_notes,
    isnull(o.multi_year_arr_c, {{ var("default_numeric") }}) as multi_year_arr,
    isnull(o.multi_year_order_c, {{ var("default_boolean") }}) as multi_year_order,
    isnull(o.netsuite_id_c, '{{ var("default_varchar") }}') as netsuite_id,
    isnull(o.new_biz_arr_trigger_c, {{ var("default_numeric") }}) as new_biz_arr_trigger,
    isnull(o.nnarr_c, {{ var("default_numeric") }}) as nnarr,
    isnull(o.nrr_renewal_c, {{ var("default_numeric") }}) as nrr_renewal,
    isnull(o.number_of_schools_c, {{ var("default_numeric") }}) as number_of_schools,
    isnull(o.number_of_students_c, {{ var("default_numeric") }}) as number_of_students,
    isnull(rt.name, '{{ var("default_varchar") }}') as opp_record_type,
    isnull(o.number_c, '{{ var("default_varchar") }}') as opportunity_number,
    isnull(o.opportunity_score_id, '{{ var("default_varchar") }}') as opportunity_score_id,
    isnull(o.owner_id, '{{ var("default_ID") }}') as owner_id,
    isnull(o.Override_ARR_c, {{ var("default_numeric") }}) as Override_ARR,
    isnull(o.paid_date_c, '{{ var("default_date") }}') as paid_date,
    isnull(o.payment_terms_c, '{{ var("default_varchar") }}') as payment_terms,
    isnull(o.po_amount_c, {{ var("default_numeric") }}) as po_amount,
    isnull(o.po_number_c, '{{ var("default_varchar") }}') as po_number,
    isnull(o.price_increase_arr_c, {{ var("default_numeric") }}) as price_increase_arr,
    isnull(o.pricebook_2_id, '{{ var("default_varchar") }}') as pricebook_2_id,
    isnull(o.probability, {{ var("default_numeric") }}) as probability,
    isnull(o.progressive_billing_c, {{ var("default_boolean") }}) as progressive_billing,
    isnull(q.progressive_payment_amount_2_c, {{ var("default_numeric") }}) as progressive_payment_amount_2,
    isnull(q.progressive_payment_amount_3_c, {{ var("default_numeric") }}) as progressive_payment_amount_3,
    isnull(q.progressive_payment_amount_4_c, {{ var("default_numeric") }}) as progressive_payment_amount_4,
    isnull(q.progressive_payment_amount_5_c, {{ var("default_numeric") }}) as progressive_payment_amount_5,
    isnull(q.progressive_payment_date_2_c, '{{ var("default_date") }}') as progressive_payment_date_2,
    isnull(q.progressive_payment_date_3_c, '{{ var("default_date") }}') as progressive_payment_date_3,
    isnull(q.progressive_payment_date_4_c, '{{ var("default_date") }}') as progressive_payment_date_4,
    isnull(q.progressive_payment_date_5_c, '{{ var("default_date") }}') as progressive_payment_date_5,
    isnull(o.quota_c,   '{{ var("default_varchar") }}') as quota ,
    isnull(o.quote_contract_type_c,   '{{ var("default_varchar") }}') as quote_contract_type ,
    isnull(o.quote_created_date_c,   '{{ var("default_date") }}') as quote_created_date ,
    isnull(o.quote_expiry_date_c,   '{{ var("default_date") }}') as quote_expiry_date ,
    isnull(o.quote_list_amount_c , {{ var("default_numeric") }}) as quote_list_amount ,
    isnull(o.quote_name_c,   '{{ var("default_varchar") }}') as quote_name ,
    isnull(o.quote_notes_c,   '{{ var("default_varchar") }}') as quote_notes ,
    isnull(o.quote_start_date_c,   '{{ var("default_date") }}') as quote_start_date ,
    isnull(o.renewable_revenue_c, {{ var("default_numeric") }}) as renewable_revenue,
    isnull(o.renewal_opportunity_c, '{{ var("default_varchar") }}') as renewal_opportunity_id,
    isnull(o.sbqq_primary_quote_c, '{{ var("default_varchar") }}') as sbqq_primary_quote,
    isnull(o.school_list_c, '{{ var("default_varchar") }}') as school_list,
    isnull(o.source_opp_arr_c, {{ var("default_numeric") }}) as source_opp_arr,
    isnull(o.stage_name, '{{ var("default_varchar") }}') as stage_name,
    isnull(o.start_date_c, '{{ var("default_date") }}') as start_date,
    isnull(o.subscription_end_date_c,   '{{ var("default_date") }}') as subscription_end_date ,
    isnull(o.subscription_start_date_c,   '{{ var("default_date") }}') as subscription_start_date ,
    isnull(o.subscription_term_c, '{{ var("default_numeric") }}') as subscription_term,
    isnull(o.total_arr_bookings_c, {{ var("default_numeric") }}) as total_arr_bookings,
    isnull(o.true_arr_c, {{ var("default_numeric") }}) as true_arr,
    isnull(o.true_arr_formula_c, {{ var("default_numeric") }}) as true_arr_formula,
    isnull(o.true_renewal_arr_c, {{ var("default_numeric") }}) as true_renewal_arr,
    isnull(o.x_1_st_contact_c, '{{ var("default_ID") }}') as x_1_st_contact,
    isnull(o.x_1_st_contact_email_c, '{{ var("default_varchar") }}') as x_1_st_contact_email,
    isnull(o.x_1_st_contact_name_c, '{{ var("default_varchar") }}') as x_1_st_contact_name,
    isnull(o.x_1_st_contact_role_c, '{{ var("default_varchar") }}') as x_1_st_contact_role,
    isnull(o.x_2_nd_contact_c, '{{ var("default_ID") }}') as x_2_nd_contact,
    isnull(o.x_2_nd_contact_email_c, '{{ var("default_varchar") }}') as x_2_nd_contact_email,
    isnull(o.x_2_nd_contact_name_c, '{{ var("default_varchar") }}') as x_2_nd_contact_name,
    isnull(o.x_3_rd_contact_c, '{{ var("default_ID") }}') as x_3_rd_contact,   
    isnull(o.x_3_rd_contact_email_c, '{{ var("default_varchar") }}') as x_3_rd_contact_email,
    isnull(o.x_3_rd_contact_name_c, '{{ var("default_varchar") }}') as x_3_rd_contact_name
from
staging as o
left outer join  {{ ref('dim_account') }} as a
on o.account_id = a.SFDC_account_id
left outer join {{ source('fivetran_salesforce_quickstart', 'record_type') }} rt
on o.record_type_id = rt.id
left outer join staging_quote as q
on o.sbqq_primary_quote_c = q.id
left outer join {{ ref("hubspot_deal") }} as hd
on o.id = hd.sfdc_opportunity_id
where o.test_account_c = false
)
select
    opportunity_id::varchar(300),
    name::varchar(300),
    account_id::varchar(300),
    sfdc_account_id::varchar(300),
    round(amount::numeric(38,10),2)::numeric(16,2) as amount,
    round(amount_won::numeric(38,10),2)::numeric(16,2) as amount_won,
    arr_bands::varchar(30),
    round(arr::numeric(38,10),2)::numeric(16,2) as arr,
    round(arr_new_business::numeric(38,10),2)::numeric(16,2) as arr_new_business,
    round(arr_renewal::numeric(38,10),2)::numeric(16,2) as arr_renewal,
    round(arr_upsell::numeric(38,10),2)::numeric(16,2) as arr_upsell,
    round(arr_won::numeric(38,10),2)::numeric(16,2) as arr_won,
    billing_addressee::varchar(160),
    billing_city::varchar(120),
    billing_state::varchar(780),
    billing_street::varchar(780),
    billing_zipcode::varchar(120),
    campaign_id::varchar(300),
    contact_id::varchar(300),
    churn_date::date,
    round(churn_formula::numeric(38,10),2)::numeric(16,2) as churn_formula,
    close_date::date,
    round(combined_arr::numeric(38,10),2)::numeric(16,2) as combined_arr,
    contract_id::varchar(30),
    created_by_id::varchar(30),
    created_date::timestamp,
    description::varchar(max),
    disable_auto_renewal_opp::boolean,
    round(multi_year_discount_rate::numeric(38,10),4)::numeric(16,4) as multi_year_discount_rate,
    contract_type::varchar(20),
    round(downsell::numeric(38,10),2)::numeric(16,2) as downsell,
    end_date::date,
    ecommerce_cart::varchar(20),
    invoiced_date::date,
    last_modified_by_id::varchar(30),
    last_modified_date::timestamp,
    license_provisioned_date ::date	,
    license_unenforced::boolean,
    loss_reason::varchar(765),
    loss_notes::varchar(3000),
    round(multi_year_arr::numeric(38,10),2)::numeric(16,2) as multi_year_arr,
    multi_year_order::boolean,
    netsuite_id::varchar(780),
    round(new_biz_arr_trigger::numeric(38,10),2)::numeric(16,2) as new_biz_arr_trigger,
    round(nnarr::numeric(38,10),2)::numeric(16,2) as nnarr,
    round(nrr_renewal::numeric(38,10),2)::numeric(16,2) as nrr_renewal,
    round(number_of_schools::numeric(38,10),0)::integer as number_of_schools,
    round(number_of_students::numeric(38,10),0)::integer as number_of_students,
    opp_record_type::varchar(20),
    opportunity_number::varchar(100),
    opportunity_score_id::varchar(30),
    owner_id::varchar(300),
    round(Override_ARR::numeric(38,10),2)::numeric(16,2) as Override_ARR,
    paid_date::date,
    payment_terms::varchar(780),
    round(po_amount::numeric(38,10),2)::numeric(16,2) as po_amount,
    po_number::varchar(90),
    round(price_increase_arr::numeric(38,10),2)::numeric(16,2) as price_increase_arr,
    pricebook_2_id::varchar(30),
    round(probability::numeric(38,10),2)::numeric(16,2) as probability,
    progressive_billing::boolean,
    round(progressive_payment_amount_2::numeric(38,10),2)::numeric(16,2) as progressive_payment_amount_2,
    round(progressive_payment_amount_3::numeric(38,10),2)::numeric(16,2) as progressive_payment_amount_3,
    round(progressive_payment_amount_4::numeric(38,10),2)::numeric(16,2) as progressive_payment_amount_4,
    round(progressive_payment_amount_5::numeric(38,10),2)::numeric(16,2) as progressive_payment_amount_5,
    progressive_payment_date_2::date,
    progressive_payment_date_3::date,
    progressive_payment_date_4::date,
    progressive_payment_date_5::date,    
    quota::varchar(250)	,
    quote_contract_type::varchar(780)	,
    quote_created_date::date	,
    quote_expiry_date::date	,
    round(quote_list_amount::numeric(38,10),2)::numeric(16,2) as quote_list_amount	,
    quote_name::varchar(250)	,
    quote_notes::varchar(780)	,
    quote_start_date::date	,
    round(renewable_revenue::numeric(38,10),2)::numeric(16,2) as renewable_revenue,
    renewal_opportunity_id::varchar(300),
    sbqq_primary_quote::varchar(30),
    school_list::varchar(max),
    round(source_opp_arr::numeric(38,10),2)::numeric(16,2) as source_opp_arr,
    stage_name::varchar(780),
    start_date::date,
    subscription_end_date::date	,
    subscription_start_date::date	,
    round(subscription_term::numeric(38,10),0)::integer as subscription_term	,
    round(total_arr_bookings::numeric(38,10),2)::numeric(16,2) as total_arr_bookings,
    round(true_arr::numeric(38,10),2)::numeric(16,2) as true_arr,
    round(true_arr_formula::numeric(38,10),2)::numeric(16,2) as true_arr_formula,
    round(true_renewal_arr::numeric(38,10),2)::numeric(16,2) as true_renewal_arr,
    x_1_st_contact::varchar(300),
    x_1_st_contact_email::varchar(250),
    x_1_st_contact_name::varchar(780),
    x_1_st_contact_role::varchar(780),
    x_2_nd_contact::varchar(300),
    x_2_nd_contact_email::varchar(250),
    x_2_nd_contact_name::varchar(780),
    x_3_rd_contact::varchar(300),
    x_3_rd_contact_email::varchar(250),
    x_3_rd_contact_name::varchar(780),
    '{{ var("loaddate") }}'::timestamp as loaddate
from data
