{{
    config(

        materialized='table',        
        sort='start_date', 
        dist='account_id'      )
}}
with data as (
select 
isnull(o.id,   '{{ var("default_varchar") }}') as opportunity_id ,
isnull(o.name,   '{{ var("default_varchar") }}') as name ,
isnull(a.account_id,   '{{ var("default_ID") }}') as account_id ,
isnull(o.account_id,   '{{ var("default_ID") }}') as SFDC_account_id ,
isnull(o.account_manager_c,   '{{ var("default_varchar") }}') as account_manager ,
isnull(o.account_name_email_c,   '{{ var("default_varchar") }}') as account_name_email ,
isnull(o.account_owner_set_c, {{ var("default_boolean") }}) as account_owner_set ,
isnull(o.activity_metric_id,   '{{ var("default_varchar") }}') as activity_metric_id ,
isnull(o.already_booked_c, {{ var("default_boolean") }}) as already_booked ,
isnull(o.already_closed_lost_c, {{ var("default_boolean") }}) as already_closed_lost ,
isnull(o.amount , {{ var("default_numeric") }}) as amount ,
isnull(o.amount_won_c , {{ var("default_numeric") }}) as amount_won ,
isnull(o.arr_bands_c,   '{{ var("default_varchar") }}') as arr_bands ,
isnull(o.arr_c , {{ var("default_numeric") }}) as arr ,
isnull(o.arr_new_business_c , {{ var("default_numeric") }}) as arr_new_business ,
isnull(o.arr_renewal_c , {{ var("default_numeric") }}) as arr_renewal ,
isnull(o.arr_upsell_c , {{ var("default_numeric") }}) as arr_upsell ,
isnull(o.arr_won_c , {{ var("default_numeric") }}) as arr_won ,
isnull(o.assessments_c, {{ var("default_boolean") }}) as assessments ,
isnull(o.billing_addressee_c,   '{{ var("default_varchar") }}') as billing_addressee ,
isnull(o.billing_city_c,   '{{ var("default_varchar") }}') as billing_city ,
isnull(o.billing_state_c,   '{{ var("default_varchar") }}') as billing_state ,
isnull(o.billing_street_c,   '{{ var("default_varchar") }}') as billing_street ,
isnull(o.billing_zipcode_c,   '{{ var("default_varchar") }}') as billing_zipcode ,
isnull(o.churn_formula_c , {{ var("default_numeric") }}) as churn_formula ,
isnull(o.churn_process_discussed_with_customer_c, {{ var("default_boolean") }}) as churn_process_discussed_with_customer ,
isnull(o.close_date,   '{{ var("default_date") }}') as close_date ,
isnull(o.close_date_minus_last_activity_date_c , {{ var("default_numeric") }}) as close_date_minus_last_activity_date ,
isnull(o.close_month_c , {{ var("default_numeric") }}) as close_month ,
isnull(o.close_year_c , {{ var("default_numeric") }}) as close_year ,
isnull(o.closed_won_date_time_c,   '{{ var("default_date") }}') as closed_won_date_time ,
isnull(o.codesters_has_licenses_synced_c, {{ var("default_boolean") }}) as codesters_has_licenses_synced ,
isnull(o.codesters_number_of_licenses_c , {{ var("default_numeric") }}) as codesters_number_of_licenses ,
isnull(o.codesters_number_of_synced_licenses_c , {{ var("default_numeric") }}) as codesters_number_of_synced_licenses ,
isnull(o.codesters_order_to_be_extended_c, {{ var("default_boolean") }}) as codesters_order_to_be_extended ,
isnull(o.codesters_order_to_be_unenforced_c, {{ var("default_boolean") }}) as codesters_order_to_be_unenforced ,
isnull(o.codesters_renewal_c, {{ var("default_boolean") }}) as codesters_renewal ,
isnull(o.combined_arr_c , {{ var("default_numeric") }}) as combined_arr ,
isnull(o.contract_id,   '{{ var("default_varchar") }}') as contract_id ,
isnull(o.created_by_id,   '{{ var("default_varchar") }}') as created_by_id ,
isnull(o.created_date,   '{{ var("default_date") }}') as created_date ,
isnull(o.created_month_1_c , {{ var("default_numeric") }}) as created_mon ,
isnull(o.created_month_c,   '{{ var("default_date") }}') as created_month ,
isnull(o.created_year_c , {{ var("default_numeric") }}) as created_year ,
isnull(o.csm_email_c,   '{{ var("default_varchar") }}') as csm_email ,
isnull(o.csm_introduced_c, {{ var("default_boolean") }}) as csm_introduced ,
isnull(o.csm_name_c,   '{{ var("default_varchar") }}') as csm_name ,
isnull(o.data_deletion_archiving_discussed_c, {{ var("default_boolean") }}) as data_deletion_archiving_discussed ,
isnull(o.data_quality_description_c,   '{{ var("default_varchar") }}') as data_quality_description ,
isnull(o.data_quality_score_c , {{ var("default_numeric") }}) as data_quality_score ,
isnull(o.days_open_c , {{ var("default_numeric") }}) as days_open ,
isnull(o.days_past_due_c , {{ var("default_numeric") }}) as days_past_due ,
isnull(o.days_since_last_activity_c , {{ var("default_numeric") }}) as days_since_last_activity ,
isnull(o.deal_docs_completed_c, {{ var("default_boolean") }}) as deal_docs_completed ,
isnull(o.description,   '{{ var("default_varchar") }}') as description ,
isnull(o.disable_auto_renewal_opp_c, {{ var("default_boolean") }}) as disable_auto_renewal_opp ,
isnull(o.disable_odc_c, {{ var("default_boolean") }}) as disable_odc ,
isnull(o.district_business_sub_type_c,   '{{ var("default_varchar") }}') as district_business_sub_type ,
isnull(o.district_enrollment_c,   '{{ var("default_varchar") }}') as district_enrollment ,
isnull(o.downsell_c , {{ var("default_numeric") }}) as downsell ,
isnull(o.end_date_c,   '{{ var("default_date") }}') as end_date ,
isnull(o.expected_new_business_arr_c , {{ var("default_numeric") }}) as expected_new_business_arr ,
isnull(o.expected_revenue , {{ var("default_numeric") }}) as expected_revenue ,
isnull(o.fiscal,   '{{ var("default_varchar") }}') as fiscal ,
isnull(o.forecast_category,   '{{ var("default_varchar") }}') as forecast_category ,
isnull(o.forecast_category_name,   '{{ var("default_varchar") }}') as forecast_category_name ,
isnull(o.has_coding_discount_c, {{ var("default_boolean") }}) as has_coding_discount ,
isnull(o.has_easy_tech_c, {{ var("default_boolean") }}) as has_easy_tech ,
isnull(o.has_open_activity, {{ var("default_boolean") }}) as has_open_activity ,
isnull(o.has_opportunity_line_item, {{ var("default_boolean") }}) as has_opportunity_line_item ,
isnull(o.has_overdue_task, {{ var("default_boolean") }}) as has_overdue_task ,
isnull(o.has_started_with_students_c, {{ var("default_boolean") }}) as has_started_with_students ,
isnull(o.house_account_c, {{ var("default_boolean") }}) as house_account ,
isnull(o.initial_interest_c,   '{{ var("default_varchar") }}') as initial_interest ,
isnull(o.international_reseller_c, {{ var("default_boolean") }}) as international_reseller ,
isnull(o.introduction_of_quote_c,   '{{ var("default_varchar") }}') as introduction_of_quote ,
isnull(o.is_closed, {{ var("default_boolean") }}) as is_closed ,
isnull(o.is_pd_resources_offered_c, {{ var("default_boolean") }}) as is_pd_resources_offered ,
isnull(o.is_won, {{ var("default_boolean") }}) as is_won ,
isnull(o.jitterbit_fulfilled_c, {{ var("default_boolean") }}) as jitterbit_fulfilled ,
isnull(o.last_modified_by_id,   '{{ var("default_varchar") }}') as last_modified_by_id ,
isnull(o.last_modified_date,   '{{ var("default_date") }}') as last_modified_date ,
isnull(o.last_stage_change_date,   '{{ var("default_date") }}') as last_stage_change_date ,
isnull(o.les_opp_c, {{ var("default_boolean") }}) as les_opp ,
isnull(o.license_unenforced_c, {{ var("default_boolean") }}) as license_unenforced ,
isnull(o.migrated_c, {{ var("default_boolean") }}) as migrated ,
isnull(o.multi_year_arr_c , {{ var("default_numeric") }}) as multi_year_arr ,
isnull(o.multi_year_c, {{ var("default_boolean") }}) as multi_year ,
isnull(o.multi_year_discussed_c, {{ var("default_boolean") }}) as multi_year_discussed ,
isnull(o.multi_year_order_c, {{ var("default_boolean") }}) as multi_year_order ,
isnull(o.needs_analysis_conducted_c, {{ var("default_boolean") }}) as needs_analysis_conducted ,
isnull(o.net_suite_order_id_c,   '{{ var("default_varchar") }}') as net_suite_order_id ,
isnull(o.netsuite_id_c,   '{{ var("default_varchar") }}') as netsuite_id ,
isnull(o.new_biz_arr_trigger_c , {{ var("default_numeric") }}) as new_biz_arr_trigger ,
isnull(o.next_step,   '{{ var("default_varchar") }}') as next_step ,
isnull(o.nnarr_c , {{ var("default_numeric") }}) as nnarr ,
isnull(o.no_integration_needed_c, {{ var("default_boolean") }}) as no_integration_needed ,
isnull(o.nrr_renewal_c , {{ var("default_numeric") }}) as nrr_renewal ,
isnull(o.number_of_products_c , {{ var("default_numeric") }}) as number_of_products ,
isnull(o.number_of_schools_c , {{ var("default_numeric") }}) as number_of_schools ,
isnull(o.odc_sent_c, {{ var("default_boolean") }}) as odc_sent ,
isnull(o.of_months_c , {{ var("default_numeric") }}) as of_months ,
isnull(o.opp_record_type_c,   '{{ var("default_varchar") }}') as opp_record_type ,
isnull(o.opp_to_be_closed_c, {{ var("default_boolean") }}) as opp_to_be_closed ,
isnull(o.opportunity_number_c,   '{{ var("default_varchar") }}') as opportunity_number ,
isnull(o.opportunity_score_id,   '{{ var("default_varchar") }}') as opportunity_score_id ,
isnull(o.order_unenforced_c, {{ var("default_boolean") }}) as order_unenforced ,
isnull(o.original_close_date_c,   '{{ var("default_date") }}') as original_close_date ,
isnull(o.original_opp_owner_1_c,   '{{ var("default_varchar") }}') as original_opp_owner ,
isnull(o.otc_email_sent_c, {{ var("default_boolean") }}) as otc_email_sent ,
isnull(o.other_c, {{ var("default_boolean") }}) as other ,
isnull(o.owner_closed_won_c , {{ var("default_numeric") }}) as owner_closed_won ,
isnull(o.owner_email_c,   '{{ var("default_varchar") }}') as owner_email ,
isnull(o.owner_id,   '{{ var("default_varchar") }}') as owner_id ,
isnull(o.owner_open_pipeline_c , {{ var("default_numeric") }}) as owner_open_pipeline ,
isnull(o.owner_quota_c , {{ var("default_numeric") }}) as owner_quota ,
isnull(o.owner_role_c,   '{{ var("default_varchar") }}') as owner_role ,
isnull(o.owner_sales_quota_c , {{ var("default_numeric") }}) as owner_sales_quota ,
isnull(o.payment_terms_c,   '{{ var("default_varchar") }}') as payment_terms ,
isnull(o.pd_scheduled_c, {{ var("default_boolean") }}) as pd_scheduled ,
isnull(o.pd_services_c, {{ var("default_boolean") }}) as pd_services ,
isnull(o.pipeline_needed_to_hit_quota_c , {{ var("default_numeric") }}) as pipeline_needed_to_hit_quota ,
isnull(o.platform_name_c,   '{{ var("default_varchar") }}') as platform_name ,
isnull(o.po_amount_c , {{ var("default_numeric") }}) as po_amount ,
isnull(o.po_amount_matches_primary_quote_amount_c, {{ var("default_boolean") }}) as po_amount_matches_primary_quote_amount ,
isnull(o.po_hold_c, {{ var("default_boolean") }}) as po_hold ,
isnull(o.po_number_c,   '{{ var("default_varchar") }}') as po_number ,
isnull(o.po_received_c, {{ var("default_boolean") }}) as po_received ,
isnull(o.po_received_counter_c , {{ var("default_numeric") }}) as po_received_counter ,
isnull(o.po_received_date_c,   '{{ var("default_date") }}') as po_received_date ,
isnull(o.price_increase_arr_c , {{ var("default_numeric") }}) as price_increase_arr ,
isnull(o.pricebook_2_id,   '{{ var("default_varchar") }}') as pricebook_2_id ,
isnull(o.primary_quote_approved_c, {{ var("default_boolean") }}) as primary_quote_approved ,
isnull(o.probability , {{ var("default_numeric") }}) as probability ,
isnull(o.progressive_billing_c, {{ var("default_boolean") }}) as progressive_billing ,
isnull(o.purchase_level_c,   '{{ var("default_varchar") }}') as purchase_level ,
isnull(o.purchase_level_number_c , {{ var("default_numeric") }}) as purchase_level_number ,
isnull(o.push_count , {{ var("default_numeric") }}) as push_count ,
isnull(o.pushed_out_c, {{ var("default_boolean") }}) as pushed_out ,
isnull(o.quota_c,   '{{ var("default_varchar") }}') as quota ,
isnull(o.quote_contract_type_c,   '{{ var("default_varchar") }}') as quote_contract_type ,
isnull(o.quote_created_date_c,   '{{ var("default_date") }}') as quote_created_date ,
isnull(o.quote_expiry_date_c,   '{{ var("default_date") }}') as quote_expiry_date ,
isnull(o.quote_list_amount_c , {{ var("default_numeric") }}) as quote_list_amount ,
isnull(o.quote_name_c,   '{{ var("default_varchar") }}') as quote_name ,
isnull(o.quote_notes_c,   '{{ var("default_varchar") }}') as quote_notes ,
isnull(o.quote_start_date_c,   '{{ var("default_date") }}') as quote_start_date ,
isnull(o.quote_synced_c, {{ var("default_boolean") }}) as quote_synced ,
isnull(o.quote_total_discount_c , {{ var("default_numeric") }}) as quote_total_discount ,
isnull(o.rai_c, {{ var("default_boolean") }}) as rai ,
isnull(o.rebuilt_during_migration_c, {{ var("default_boolean") }}) as rebuilt_during_migration ,
isnull(o.record_type_id,   '{{ var("default_varchar") }}') as record_type_id ,
isnull(o.references_provided_c, {{ var("default_boolean") }}) as references_provided ,
isnull(o.remaining_quota_c , {{ var("default_numeric") }}) as remaining_quota ,
isnull(o.renewable_revenue_c , {{ var("default_numeric") }}) as renewable_revenue ,
isnull(o.renewal_at_79_c , {{ var("default_numeric") }}) as renewal_at_79 ,
isnull(o.renewal_biz_trigger_c , {{ var("default_numeric") }}) as renewal_biz_trigger ,
isnull(o.renewal_owner_email_c,   '{{ var("default_varchar") }}') as renewal_owner_email ,
isnull(o.rep_says_go_c, {{ var("default_boolean") }}) as rep_says_go ,
isnull(o.reseller_class_for_les_c, {{ var("default_boolean") }}) as reseller_class_for_les ,
isnull(o.risk_identified_c, {{ var("default_boolean") }}) as risk_identified ,
isnull(o.risk_opportunity_c, {{ var("default_boolean") }}) as risk_opportunity ,
isnull(o.sales_support_rep_c,   '{{ var("default_varchar") }}') as sales_support_rep ,
isnull(o.sbqq_contracted_c, {{ var("default_boolean") }}) as sbqq_contracted ,
isnull(o.sbqq_ordered_c, {{ var("default_boolean") }}) as sbqq_ordered ,
isnull(o.sbqq_primary_quote_c,   '{{ var("default_varchar") }}') as sbqq_primary_quote ,
isnull(o.sbqq_renewal_c, {{ var("default_boolean") }}) as sbqq_renewal ,
isnull(o.school_list_c,   '{{ var("default_varchar") }}') as school_list ,
isnull(o.school_year_c,   '{{ var("default_varchar") }}') as school_year ,
isnull(o.send_odc_c, {{ var("default_boolean") }}) as send_odc ,
isnull(o.set_initial_new_biz_arr_amount_c, {{ var("default_boolean") }}) as set_initial_new_biz_arr_amount ,
isnull(o.set_up_for_processing_c, {{ var("default_boolean") }}) as set_up_for_processing ,
isnull(o.source_opp_arr_c , {{ var("default_numeric") }}) as source_opp_arr ,
isnull(o.spring_promo_c, {{ var("default_boolean") }}) as spring_promo ,
isnull(o.stage_name,   '{{ var("default_varchar") }}') as stage_name ,
isnull(o.stakeholders_confirmed_c, {{ var("default_boolean") }}) as stakeholders_confirmed ,
isnull(o.start_date_c,   '{{ var("default_date") }}') as start_date ,
isnull(o.subscription_end_date_c,   '{{ var("default_date") }}') as subscription_end_date ,
isnull(o.subscription_start_date_c,   '{{ var("default_date") }}') as subscription_start_date ,
isnull(o.subscription_term_c , {{ var("default_numeric") }}) as subscription_term ,
isnull(o.success_plan_agreed_upon_c, {{ var("default_boolean") }}) as success_plan_agreed_upon ,
isnull(o.success_plan_shared_c, {{ var("default_boolean") }}) as success_plan_shared ,
isnull(o.system_modstamp,   '{{ var("default_date") }}') as system_modstamp ,
isnull(o.test_account_c, {{ var("default_boolean") }}) as test_account ,
isnull(o.total_arr_bookings_c , {{ var("default_numeric") }}) as total_arr_bookings ,
isnull(o.total_credit_from_opp_product_c , {{ var("default_numeric") }}) as total_credit_from_opp_product ,
isnull(o.total_opportunity_quantity , {{ var("default_numeric") }}) as total_opportunity_quantity ,
isnull(o.training_session_created_c, {{ var("default_boolean") }}) as training_session_created ,
isnull(o.true_arr_c , {{ var("default_numeric") }}) as true_arr ,
isnull(o.true_arr_formula_c , {{ var("default_numeric") }}) as true_arr_formula ,
isnull(o.true_renewal_arr_c , {{ var("default_numeric") }}) as true_renewal_arr ,
isnull(o.type,   '{{ var("default_varchar") }}') as type ,
isnull(o.update_close_date_c, {{ var("default_boolean") }}) as update_close_date ,
isnull(o.validation_bypass_date_time_c,   '{{ var("default_date") }}') as validation_bypass_date_time ,
isnull(o.variance_c , {{ var("default_numeric") }}) as variance ,
isnull(o.vendor_of_choice_c, {{ var("default_boolean") }}) as vendor_of_choice ,
isnull(o.verbal_commitment_c, {{ var("default_boolean") }}) as verbal_commitment ,
isnull(o.x_1_st_contact_c,   '{{ var("default_varchar") }}') as x_1_st_contact ,
isnull(o.x_1_st_contact_email_c,   '{{ var("default_varchar") }}') as x_1_st_contact_email ,
isnull(o.x_1_st_contact_name_c,   '{{ var("default_varchar") }}') as x_1_st_contact_name ,
isnull(o.x_1_st_contact_role_c,   '{{ var("default_varchar") }}') as x_1_st_contact_role ,
isnull(o.x_18_for_12_c, {{ var("default_boolean") }}) as x_18_for_12 ,
isnull(o.x_30_days_from_being_closed_lost_c, {{ var("default_boolean") }}) as x_30_days_from_being_closed_lost 
from
{{ source('fivetran_salesforce_quickstart', 'opportunity') }} as o
left outer join  {{ ref('dim_account') }} as a
on o.account_id = a.SFDC_account_id
)
select
opportunity_id::varchar(300) ,
name::varchar(300),
account_id::varchar(300),
SFDC_account_id::varchar(300) ,
account_manager::varchar(30)	,
account_name_email::varchar(780)	,
account_owner_set::boolean	,
activity_metric_id::varchar(30)	,
already_booked::boolean	,
already_closed_lost::boolean	,
amount::numeric(35,10)	,
amount_won::numeric(35,10)	,
arr_bands::varchar(30)	,
arr::double precision	,
arr_new_business::numeric(38,10)	,
arr_renewal::numeric(38,10)	,
arr_upsell::numeric(38,10)	,
arr_won::numeric(38,10)	,
assessments::boolean	,
billing_addressee::varchar(160)	,
billing_city::varchar(120)	,
billing_state::varchar(780)	,
billing_street::varchar(780)	,
billing_zipcode::varchar(120)	,
churn_formula::double precision	,
churn_process_discussed_with_customer::boolean	,
close_date::date	,
close_date_minus_last_activity_date::numeric(25,10)	,
close_month::integer	,
close_year::integer	,
closed_won_date_time::timestamp	,
codesters_has_licenses_synced::boolean	,
codesters_number_of_licenses::bigint	,
codesters_number_of_synced_licenses::bigint	,
codesters_order_to_be_extended::boolean	,
codesters_order_to_be_unenforced::boolean	,
codesters_renewal::boolean	,
combined_arr::numeric(38,10)	,
contract_id::varchar(30)	,
created_by_id::varchar(30)	,
created_date::timestamp	,
created_mon::integer	,
created_month::date	,
created_year::integer	,
csm_email::varchar(400)	,
csm_introduced::boolean	,
csm_name::varchar(380)	,
data_deletion_archiving_discussed::boolean	,
data_quality_description::varchar(70)	,
data_quality_score::integer	,
days_open::numeric(25,10)	,
days_past_due::numeric(25,10)	,
days_since_last_activity::numeric(25,10)	,
deal_docs_completed::boolean	,
description::varchar(max)	,
disable_auto_renewal_opp::boolean	,
disable_odc::boolean	,
district_business_sub_type::varchar(20)	,
district_enrollment::varchar(40)	,
downsell::double precision	,
end_date::date	,
expected_new_business_arr::double precision	,
expected_revenue::numeric(35,10)	,
fiscal::varchar(20)	,
forecast_category::varchar(130)	,
forecast_category_name::varchar(780)	,
has_coding_discount::boolean	,
has_easy_tech::boolean	,
has_open_activity::boolean	,
has_opportunity_line_item::boolean	,
has_overdue_task::boolean	,
has_started_with_students::boolean	,
house_account::boolean	,
initial_interest::varchar(780),
international_reseller::boolean	,
introduction_of_quote::varchar(780)	,
is_closed::boolean	,
is_pd_resources_offered::boolean	,
is_won::boolean	,
jitterbit_fulfilled::boolean	,
last_modified_by_id::varchar(30)	,
last_modified_date::timestamp	,
last_stage_change_date::timestamp	,
les_opp::boolean	,
license_unenforced::boolean	,
migrated::boolean	,
multi_year_arr::numeric(38,10)	,
multi_year::boolean	,
multi_year_discussed::boolean	,
multi_year_order::boolean	,
needs_analysis_conducted::boolean	,
net_suite_order_id::varchar(90)	,
netsuite_id::varchar(780)	,
new_biz_arr_trigger::numeric(38,10)	,
next_step::varchar(780)	,
nnarr::double precision	,
no_integration_needed::boolean	,
nrr_renewal::numeric(38,10)	,
number_of_products::bigint	,
number_of_schools::double precision	,
odc_sent::boolean	,
of_months::double precision	,
opp_record_type::varchar(20)	,
opp_to_be_closed::boolean	,
opportunity_number::varchar(100)	,
opportunity_score_id::varchar(30)	,
order_unenforced::boolean	,
original_close_date::date	,
original_opp_owner::varchar(30)	,
otc_email_sent::boolean	,
other::boolean	,
owner_closed_won::double precision	,
owner_email::varchar(250)	,
owner_id::varchar(30)	,
owner_open_pipeline::double precision	,
owner_quota::double precision	,
owner_role::varchar(250)	,
owner_sales_quota::numeric(35,10)	,
payment_terms::varchar(780)	,
pd_scheduled::boolean	,
pd_services::boolean	,
pipeline_needed_to_hit_quota::double precision	,
platform_name::varchar(250)	,
po_amount::numeric(35,10)	,
po_amount_matches_primary_quote_amount::boolean	,
po_hold::boolean	,
po_number::varchar(90)	,
po_received::boolean	,
po_received_counter::integer	,
po_received_date::date	,
price_increase_arr::double precision	,
pricebook_2_id::varchar(30)	,
primary_quote_approved::boolean	,
probability::double precision	,
progressive_billing::boolean	,
purchase_level::varchar(20)	,
purchase_level_number::double precision	,
push_count::bigint	,
pushed_out::boolean	,
quota::varchar(250)	,
quote_contract_type::varchar(780)	,
quote_created_date::date	,
quote_expiry_date::date	,
quote_list_amount::double precision	,
quote_name::varchar(250)	,
quote_notes::varchar(780)	,
quote_start_date::date	,
quote_synced::boolean	,
quote_total_discount::double precision	,
rai::boolean	,
rebuilt_during_migration::boolean	,
record_type_id::varchar(30)	,
references_provided::boolean	,
remaining_quota::double precision	,
renewable_revenue::numeric(38,10)	,
renewal_at_79::numeric(38,10)	,
renewal_biz_trigger::numeric(38,10)	,
renewal_owner_email::varchar(250)	,
rep_says_go::boolean	,
reseller_class_for_les::boolean	,
risk_identified::boolean	,
risk_opportunity::boolean	,
sales_support_rep::varchar(30)	,
sbqq_contracted::boolean	,
sbqq_ordered::boolean	,
sbqq_primary_quote::varchar(30)	,
sbqq_renewal::boolean	,
school_year::varchar(780)	,
school_list::varchar(max)	,
send_odc::boolean	,
set_initial_new_biz_arr_amount::boolean	,
set_up_for_processing::boolean	,
source_opp_arr::numeric(38,10)	,
spring_promo::boolean	,
stage_name::varchar(780)	,
stakeholders_confirmed::boolean	,
start_date::date	,
subscription_end_date::date	,
subscription_start_date::date	,
subscription_term::double precision	,
success_plan_agreed_upon::boolean	,
success_plan_shared::boolean	,
system_modstamp::timestamp	,
test_account::boolean	,
total_arr_bookings::numeric(38,10)	,
total_credit_from_opp_product::double precision	,
total_opportunity_quantity::double precision	,
training_session_created::boolean	,
true_arr::numeric(35,10)	,
true_arr_formula::double precision	,
true_renewal_arr::double precision	,
type::varchar(780)	,
update_close_date::boolean	,
validation_bypass_date_time::timestamp	,
variance::numeric(36,10)	,
vendor_of_choice::boolean	,
verbal_commitment::boolean	,
x_1_st_contact::varchar(30)	,
x_1_st_contact_email::varchar(250)	,
x_1_st_contact_name::varchar(780)	,
x_1_st_contact_role::varchar(780)	,
x_18_for_12::boolean	,
x_30_days_from_being_closed_lost::boolean	,
'{{ var("loaddate") }}'::timestamp as loaddate
from data
