{{ config(materialized='ephemeral') }}

SELECT 
opportunity_line_id, 
sfdc_product_id, 
opportunity_id, 
pricebook_entry_id, 
pricebook_id, 
netsuite_sku,
sbqq_quote_line, 
name, 
quantity, 
total_price, 
unit_price, 
weighted_total_price, 
combine_new_biz_arr, 
combine_renewal_arrs, 
combine_upsell_arrs, 
list_price, 
net_price_display, 
net_unit_price, 
opportunity_product_arr, 
pro_rate_adj_term, 
record_type, 
business_type_opty_product, 
class, 
created_date,
loaddate,
additional_discount_amount,
additional_discount_rate,
additional_discount_type,
total_discount_rate,
total_discount_amount
FROM {{ ref("dim_opportunity_line") }} 
