---
version: 2
models:
  - name: dim_context
    description: Context dimension base on content_delivery_usage.dbo.context
    config:
      tags:
        - dim
  - name: dim_learning_object
    description: Learning Object (Lessons or curriculum items) dimension base on
      content_delivery_usage.dbo.learning_object
    config:
      tags:
        - dim
  - name: dim_learning_pathway
    description: Learning Pathway dimension base on
      content_delivery_usage.dbo.learning_pathway.
    config:
      tags:
        - dim
  - name: fact_assignment_completion
    description: Assignment Completion and grades Fact table base on
      content_delivery_usage.dbo.fact_assignment_completion.
    config:
      tags:
        - fact
  - name: fact_assignment_launch
    description: Assignment Launch Fact table base on
      content_delivery_usage.dbo.fact_assignment_launch.
    config:
      tags:
        - fact
