{{ config(materialized='view', 
   bind=False, 
   description="This staging view select all columns for FACT_OPPORTUNITY from SFDC Opportunity source"
   ) }}

select 
id,
name,
account_manager_c,
account_name_email_c,
activity_metric_id,
already_booked_c,
already_closed_lost_c,
amount ,
amount_won_c ,
arr_bands_c,
arr_c ,
arr_new_business_c ,
arr_renewal_c ,
arr_upsell_c ,
arr_won_c ,
assessments_c,
billing_addressee_c,
billing_city_c,
billing_state_c,
billing_street_c,
billing_zipcode_c,
churn_date_c,
churn_formula_c ,
churn_process_discussed_with_customer_c,
close_date,
close_date_minus_last_activity_date_c ,
close_month_c ,
close_year_c ,
closed_won_date_time_c,
codesters_has_licenses_synced_c,
codesters_number_of_licenses_c ,
codesters_number_of_synced_licenses_c ,
codesters_order_to_be_extended_c,
codesters_order_to_be_unenforced_c,
codesters_renewal_c,
combined_arr_c ,
contract_id,
created_by_id,
created_date AT TIME ZONE 'PST',
created_month_1_c ,
created_month_c,
created_year_c ,
csm_email_c,
csm_introduced_c,
csm_name_c,
data_deletion_archiving_discussed_c,
data_quality_description_c,
data_quality_score_c ,
days_open_c ,
days_past_due_c ,
days_since_last_activity_c ,
deal_docs_completed_c,
description,
disable_auto_renewal_opp_c,
disable_odc_c,
district_business_sub_type_c,
district_enrollment_c,
downsell_c ,
end_date_c,
expected_new_business_arr_c ,
expected_revenue ,
fiscal,
forecast_category,
forecast_category_name,
has_coding_discount_c,
has_easy_tech_c,
has_open_activity,
has_opportunity_line_item,
has_overdue_task,
has_started_with_students_c,
house_account_c,
initial_interest_c,
international_reseller_c,
introduction_of_quote_c,
invoiced_date_c,
is_closed,
is_pd_resources_offered_c,
is_won,
jitterbit_fulfilled_c,
last_modified_by_id,
last_modified_date AT TIME ZONE 'PST',
last_stage_change_date,
les_opp_c,
license_unenforced_c,
migrated_c,
multi_year_arr_c ,
multi_year_c,
multi_year_discussed_c,
multi_year_order_c,
needs_analysis_conducted_c,
net_suite_order_id_c,
netsuite_id_c,
new_biz_arr_trigger_c ,
next_step,
nnarr_c ,
no_integration_needed_c,
nrr_renewal_c ,
number_of_products_c ,
number_of_schools_c ,
odc_sent_c,
of_months_c ,
opp_record_type_c,
opp_to_be_closed_c,
opportunity_number_c,
opportunity_score_id,
order_unenforced_c,
original_close_date_c,
original_opp_owner_1_c,
otc_email_sent_c,
other_c,
owner_closed_won_c ,
owner_email_c,
owner_id,
owner_open_pipeline_c ,
owner_quota_c ,
owner_role_c,
owner_sales_quota_c ,
payment_terms_c,
pd_scheduled_c,
pd_services_c,
pipeline_needed_to_hit_quota_c ,
platform_name_c,
po_amount_c ,
po_amount_matches_primary_quote_amount_c,
po_hold_c,
po_number_c,
po_received_c,
po_received_counter_c ,
po_received_date_c,
price_increase_arr_c ,
pricebook_2_id,
primary_quote_approved_c,
probability ,
progressive_billing_c,
purchase_level_c,
purchase_level_number_c ,
push_count ,
pushed_out_c,
quota_c,
quote_contract_type_c,
quote_created_date_c,
quote_expiry_date_c,
quote_list_amount_c ,
quote_name_c,
quote_notes_c,
quote_start_date_c,
quote_synced_c,
quote_total_discount_c ,
rai_c,
rebuilt_during_migration_c,
record_type_id,
references_provided_c,
remaining_quota_c ,
renewable_revenue_c ,
renewal_at_79_c ,
renewal_biz_trigger_c ,
renewal_owner_email_c,
rep_says_go_c,
reseller_class_for_les_c,
risk_identified_c,
risk_opportunity_c,
sales_support_rep_c,
sbqq_contracted_c,
sbqq_ordered_c,
sbqq_primary_quote_c,
sbqq_renewal_c,
school_list_c,
school_year_c,
send_odc_c,
set_initial_new_biz_arr_amount_c,
set_up_for_processing_c,
source_opp_arr_c ,
spring_promo_c,
stage_name,
stakeholders_confirmed_c,
start_date_c,
subscription_end_date_c,
subscription_start_date_c,
subscription_term_c ,
success_plan_agreed_upon_c,
success_plan_shared_c,
system_modstamp,
test_account_c,
total_arr_bookings_c ,
total_credit_from_opp_product_c ,
total_opportunity_quantity ,
training_session_created_c,
true_arr_c ,
true_arr_formula_c ,
true_renewal_arr_c ,
type,
update_close_date_c,
validation_bypass_date_time_c,
variance_c ,
vendor_of_choice_c,
verbal_commitment_c,
x_1_st_contact_c,
x_1_st_contact_email_c,
x_1_st_contact_name_c,
x_1_st_contact_role_c,
x_18_for_12_c,
x_30_days_from_being_closed_lost_c	 
from
{{ source('fivetran_salesforce_quickstart', 'opportunity') }} as o