services: 
  postgres:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ../airflow_pgdata/pgdata:/var/lib/postgresql/data

  airflow-webserver:
    build: .
    image: airflow-dbt:2.10.2-py3.12
    user: "1002:0"
    group_add:
      - "1004"
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - /home/kdrogaieva/Prod/airflow_env/.env
    environment:
      HOME: /home/airflow
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/releases/current/transformations/airflow/dags
      AIRFLOW__SMTP__SMTP_HOST: "email-smtp.us-west-2.amazonaws.com"
      AIRFLOW__SMTP__SMTP_STARTTLS: "True"
      AIRFLOW__SMTP__SMTP_SSL: "False"
      AIRFLOW__SMTP__SMTP_PORT: "587"
      AIRFLOW__SMTP__SMTP_MAIL_FROM: "reportinganalytics@learning.com"
      AIRFLOW__SMTP__SMTP_USER: "AKIATT2JL77I26VH5X7R"
      AIRFLOW__SMTP__SMTP_PASSWORD_CMD: cat /opt/airflow_secrets/.smtp_password




      # dbt location inside container
      DBT_PROFILES_DIR: /home/airflow/.dbt
      DBT_LCOM_DW_PROJECT_DIR: /opt/airflow/releases/current/transformations/dbt/LCom_DW
      DBT_TARGET_PATH: /home/airflow/dbt_target
      DBT_LOG_PATH: /home/airflow/dbt_logs   

      # repo
      REPO_DIR: /opt/airflow/releases/current/transformations

    volumes:
      # Airflow runtime stuff
      - /home/kdrogaieva/Prod/airflow_logs:/opt/airflow/logs
      - /home/kdrogaieva/Prod/airflow_plugins:/opt/airflow/plugins
      - /home/kdrogaieva/Prod/dbt_profile:/home/airflow/.dbt
      - /home/kdrogaieva/Prod/releases:/opt/airflow/releases
      - /home/kdrogaieva/Prod/airflow_env:/opt/airflow_secrets:ro
      - /home/kdrogaieva/Prod/dbt_target:/home/airflow/dbt_target
      - /home/kdrogaieva/Prod/dbt_logs:/home/airflow/dbt_logs 

    
    ports:
      - "8080:8080"


    # Healthcheck for Airflow webserver
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8080/health >/dev/null || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

    command: webserver

  airflow-scheduler:
    image: airflow-dbt:2.10.2-py3.12
    user: "1002:0"
    group_add:
      - "1004"
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - /home/kdrogaieva/Prod/airflow_env/.env
    environment:
      HOME: /home/airflow
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"

      AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/releases/current/transformations/airflow/dags
      AIRFLOW__SMTP__SMTP_HOST: "email-smtp.us-west-2.amazonaws.com"
      AIRFLOW__SMTP__SMTP_STARTTLS: "True"
      AIRFLOW__SMTP__SMTP_SSL: "False"
      AIRFLOW__SMTP__SMTP_PORT: "587"
      AIRFLOW__SMTP__SMTP_MAIL_FROM: "reportinganalytics@learning.com"
      AIRFLOW__SMTP__SMTP_USER: "AKIATT2JL77I26VH5X7R"
      AIRFLOW__SMTP__SMTP_PASSWORD_CMD: cat /opt/airflow_secrets/.smtp_password

      REPO_DIR:  /opt/airflow/releases/current/transformations

      # dbt location inside container
      DBT_PROFILES_DIR: /home/airflow/.dbt
      DBT_LCOM_DW_PROJECT_DIR: /opt/airflow/releases/current/transformations/dbt/LCom_DW
      DBT_TARGET_PATH: /home/airflow/dbt_target
      DBT_LOG_PATH: /home/airflow/dbt_logs  

    volumes:
      - /home/kdrogaieva/Prod/airflow_logs:/opt/airflow/logs
      - /home/kdrogaieva/Prod/airflow_plugins:/opt/airflow/plugins
      - /home/kdrogaieva/Prod/dbt_profile:/home/airflow/.dbt
      - /home/kdrogaieva/Prod/releases:/opt/airflow/releases
      - /home/kdrogaieva/Prod/airflow_env:/opt/airflow_secrets:ro
      - /home/kdrogaieva/Prod/dbt_target:/home/airflow/dbt_target
      - /home/kdrogaieva/Prod/dbt_logs:/home/airflow/dbt_logs      

    command: scheduler

    healthcheck:
      test: ["CMD-SHELL", "pgrep -f 'airflow scheduler' >/dev/null || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  airflow-init:
    image: airflow-dbt:2.10.2-py3.12
    user: "1002:0"
    group_add:
      - "1004"
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - /home/kdrogaieva/Prod/airflow_env/.env
    environment:
      HOME: /home/airflow
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"

      # dbt location inside container
      DBT_PROFILES_DIR: /home/airflow/.dbt
      DBT_LCOM_DW_PROJECT_DIR: /opt/airflow/releases/current/transformations/dbt/LCom_DW
      DBT_TARGET_PATH: /home/airflow/dbt_target
      DBT_LOG_PATH: /home/airflow/dbt_logs   

      # repo
      REPO_DIR:  /opt/airflow/releases/current/transformations



    volumes:
      - /home/kdrogaieva/Prod/airflow_logs:/opt/airflow/logs
      - /home/kdrogaieva/Prod/airflow_plugins:/opt/airflow/plugins
      - /home/kdrogaieva/Prod/dbt_profile:/home/airflow/.dbt
      - /home/kdrogaieva/Prod/releases:/opt/airflow/releases
      - /home/kdrogaieva/Prod/airflow_env:/opt/airflow_secrets:ro
      - /home/kdrogaieva/Prod/dbt_target:/home/airflow/dbt_target
      - /home/kdrogaieva/Prod/dbt_logs:/home/airflow/dbt_logs 
    command:
      - bash
      - -c
      - "airflow db migrate && airflow users create --username admin --password \"$(tr -d '\\n' < /opt/airflow_secrets/.airflow_admin_password)\" --firstname Kate --lastname Drogaieva --role Admin --email reportinganalytics@learning.com || true"
