name: Publish Docs

on:
  workflow_run:
    workflows: ["Deploy to EC2 AWSPRDDWH001"]
    types: [completed]

env:
  PUBLISH_SCRIPT: /home/kdrogaieva/deploy/bin/publish_dbt_docs.sh

jobs:
  publish_docs:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted
    steps:
      - name: Publish docs
        shell: bash
        run: |
          "$PUBLISH_SCRIPT"